- src/str.js
- test/unit/string_functions.py
Implemented:
```
str.expandtabs()
str.isspace()
str.istitle()
str.splitlines()
str.swapcase()
str.title()
str.zfill(width)
```
based largely on [pypy implementations](https://github.com/woodrow/pyoac/blob/master/pypy/objspace/std/stringobject.py).  Unittests are based on cPython [buffer unittests](https://github.com/python/cpython/blob/master/Lib/test/buffer_tests.py). 
Still need to implement string.format, and get Skulpt to pass cpython [string_tests.py](https://github.com/python/cpython/blob/master/Lib/test/string_tests.py) but that's a whole other project.
> String functions

- src/compile.js
- src/import.js
This change allows imported modules to be loaded asynchronously.
> Asynchronous (suspendable) loading of imported modules

- .jscsrc
- .travis.yml
- dist-update.sh
- package.json
- skulpt.py
- src/enumerate.js
- src/str.js
Probably under-utilizing JSCS, if JShint drops more features jscs can probably fill the gap. 
fixes #320
> added jscs for indentation checking

- src/lib/image/__init__.js
I had to fix the code to match Brad's changes.
> Update to allow a pixel to store the x and y location

- src/lib/turtle/__init__.js
Updated turtle graphics module to be encapsulated in a closure that is tied
to the currently configured dom element set by Sk.TurtleGraphics.target.
This means that multiple turtle apps can be running simultaneously.
fixes #341
> Wrapped turtle module in a closure tied to DOM

- src/lib/turtle/__init__.js
Explicitly adds screen method aliases without requiring creation of an anonymous turtle
fixes #352
> Adds Screen method aliases to turtle module

- src/lib/processing/__init__.js
Here is my first contribution to Skulpt. Just making sure that this is an appropriate style, and that I took care of all of the necessary details. Let me know. Then I'll go through the rest of the processing lib and see what else is missing.
> Skulpt processing: added bezier

- src/lib/turtle/__init__.js
Previously using ondrag required also calling onclick. This is not how the Python
version works so this PR fixes ondrag such that it can be used on its own.
Essentially the MouseManager is always listening for events now and on a mousedown/mouseup
it marks any mousemove (ondrag) managers as elligible for dragging.
This PR also includes a couple of minor style fixes to get jshint happy
> Fixes ondrag implementation

- .gitignore
- skulpt.py
- src/formatting.js
- test/unit/test_strformat.py
str.format is almost 100% supported. Fixes #90, fixes #321 
Some issues remain in repr support and I have no idea how to handle kwargs, any advice is welcome.
I'm sure I have overlooked some edge cases of various combinations of formatting specifications.
> adding str.format() support

- src/compile.js
- src/object.js
In reponse to #384 I put this together.  
I would like others to have a look and make sure it seems right.
> quick stab at adding a NotImplemented constant

- src/compile.js
As suggested by @waywaaard in Issue #391
* Added Date to the _reservedNames object
* Updated Compiler.prototype.cclass to use 'fixReservedNames' method to protect class names
Fixes #391
> Adds 'Date' as a reserved name

- src/compile.js
- src/import.js
This is a partial fix for an issue that was brought up in #403.
> Correctly set canSuspend when compiling

- src/compile.js
`Date.now()` is significantly faster than `new Date()`
(http://jsperf.com/new-date-vs-date-now-vs-performance-now/28)
> Use Date.now() for timeout checks

- src/errors.js
fixes the broken build after #408
> correct closure comments

- src/abstract.js
- src/long.js
- test/unit/test_unary.py
This should be merged with #241, as it provides the fix for the provided failing tests.
> fix for #241  invert longs

- src/lib/unittest/__init__.py
- test/unit/test_structseq.py
assertRaises did not take the correct parameters.
> Unittest fixes

- src/builtin.js
- src/builtindict.js
- test/unit/test_builtin.py
> add setattr builtin and tests

- CONTRIBUTING.md
So as not to break our own new rules, I even made a PR to update CONTRIBUTING.md
> update the contributing doc with the committers information

- src/lib/random.js
- test/unit/test_random.py
My first real code contribution :tada: A small one but a special request from a MOOC we're working with that goes live on Monday.
~~I need a little help on the tests though.  Tried to be a good citizen and do unittest style.  I hacked the official Python test of uniform distribution as best I could and it's passing Python but not Skulpt.  In Skulpt I'm getting an error about concatenating strs and ints on line 134 of the test file, which doesn't exist.  Anyone feeling charitable and willing to help me debug the test?~~
**Edit: Tests are now fixed thanks to #445.  This is ready for review**
(There's not a lot I could use from the official unittest because they use `test_support` throughout. Otherwise would've included all the passing Random tests).
> Random.uniform

- src/builtin.js
- test/unit/test_builtin.py
> Bugfix dir (also removes __name__ from output)

- src/str.js
> don't use string.trimLeft use goog.string.trimLeft

- src/list.js
- test/unit/test_list_sort.py
> unpack reverse before comparison

- .jscsrc
- .travis.yml
- src/abstract.js
- src/biginteger.js
- src/bool.js
- src/builtin.js
- src/dict.js
- src/enumerate.js
- src/ffi.js
- src/file.js
- src/float.js
- src/formatting.js
- src/function.js
- src/generator.js
- src/import.js
- src/list.js
- src/method.js
- src/misceval.js
- src/number.js
- src/object.js
- src/parser.js
- src/slice.js
- src/sorted.js
- src/str.js
- src/structseq.js
- src/timsort.js
- src/tuple.js
- src/type.js
As talked about in #415 adds stricter rules to jscs and shows versions on travis so you can compare to your local env.
> Tweaking build (jscs and jshint)

- src/object.js
- src/type.js
- test/unit/test_dict.py
All tests except for the dict update unit test test pass.  Not sure why but there is a comment about Skulpt previously not supporting something with iteration.  So that seems likely.  @rixner any ideas?
> Betteriter  -- Fixes 469

- src/abstract.js
- src/builtin.js
- src/misceval.js
Automatic merge of #484 broke the build as it was not properly rebased off master. This PR fixes those bugs.
> Fix bugs introduced by merging #484

- src/lib/unittest/__init__.py
- src/lib/unittest/gui.py
Just a couple of simple changes to make unittest play nice when the ``Sk.python3`` flag is set.  And a couple of updates to the GUI module to keep up with the latest skulpt developments.
This is no substitute for getting ``from future`` stuff integrated into the unittests, but it doesn't get in the way either.
> update unittest.gui to be compatible with latest skulpt updates

- HACKING.md
Just updated a couple typos in HACKING.md
And I saw that there was a need for some documentation to be done? Are there any instructions on how to do this? I also saw the `gh-pages` branch. I could help out there?
Related: 
- https://github.com/skulpt/skulpt/issues/182
- https://github.com/skulpt/skulpt/issues/454
Although after further exploration, it looks like it has moved to: http://www.skulpt.org/static/developer.html
Very cool project ya'll.
> HACKING.md updated typos

- .gitignore
- skulpt.py
- support/d8/tools/SourceMap.js
- support/d8/tools/codemap.js
- support/d8/tools/consarray.js
- support/d8/tools/csvparser.js
- support/d8/tools/linux-tick-processor
- support/d8/tools/logreader.js
- support/d8/tools/mac-tick-processor
- support/d8/tools/profile.js
- support/d8/tools/profile_view.js
- support/d8/tools/splaytree.js
- support/d8/tools/tickprocessor-driver.js
- support/d8/tools/tickprocessor.js
- support/d8/tools/windows-tick-processor.bat
- test/test.js
I've added a few profiling tools to skulpt.py which I have found useful in assessing/improving performance in Skulpt.
```{program} profile [filename.py] [output]```
Run the Python file (or the entire test suite, if no file specified) using the d8 engine with the profiling flag set, which saves tick output in v8.log. Processes  v8.log using the d8 tick processing tools and outputs the results to the output file (or stdout, if no file specified).
Sample usage:
| Command | Result |
| --- | --- |
| `./skulpt.py profile my_profile` | Profile test suite and output processed results to my_profile |
| `./skulpt.py profile test/run/t00.py` | Profile test/run/t00.py and output processes results to stdout |
| `./skulpt.py profile temp.py temp_profile` | Profile temp.py and output processed results …
> Profiling and timing commands

- skulpt.py
- src/lib/processing.js
> Processingfix

- skulpt.py
Can someone with windows give this a quick test.  It should satisfy those with a newer / different d8 installation on windows and what the rest of us have.
> check for x32 sudir on windows

- skulpt.py
- src/builtin.js
- src/fromcodepoint.js
- test/unit/test_unichr.py
Start with the demonstration:  Lots of fancy chars, generated by unichr(...)
http://www.av8n.com/skulpt/demo/unichr.html
Heretofore, unichr() was not implemented.
This pull request provides the implementation.
I have tested this with firefox, chrome, and nodejs.
> unichr now working

- src/lib/turtle.js
I'm running multiple instances of skulpt on a page, so I added code to let me stop a turtle animation when the next one starts.  (Feature addition)
I also added e.preventDefault in a few places to help out the onkey handling in turtle code.  (Bug fix)
This is my first pull request, so please feel free to give me feedback.
Thanks!
> Minor Turtle changes

- src/int.js
- src/long.js
- test/unit/test_int.py
This does not pass tests, but I'm opening a pull request to make discussion easier.
> Integer division

- src/lib/random.js
- test/unit/test_random.py
Adds the following methods for generating random variables: random.triangular(), random.gauss(), random.lognormvariate() and random.expovariate()
> Some missing methods for generating random samples

- src/builtin.js
- src/misceval.js
> Meredydd susp try catch pr

- src/builtin.js
- test/unit/test_builtin.py
This implements the reversed() function
> Implement the reversed() builtin

- HACKING.md
- README.md
It took me a little while to figure out how to get Skulpt building so thought it would be good to add the steps to the README to help others
> Update the readme with simple steps to build skulpt

- src/lib/processing.js
Perhaps overlooked in [this commit](https://github.com/skulpt/skulpt/commit/6b7bacd0d6bd835c43f5ca9d656254106ccc7bcc).
> Fixes processing cursor constants and removes duplicate stroke constants

- src/lib/unittest/__init__.py
- test/unit/test_StringIO.py
- test/unit/test_index.py
- test/unit/test_subclass.py
- test/unit/test_time.py
Updates to allow more unittest files to pass in CPython.
> setup should be setUp in unittests.

- src/lib/unittest/__init__.py
- test/unit/test_list.py
- test/unit/test_namedtuple.py
Updates to allow more unittest files to pass in CPython.
> verbose should be verbosity in unittest.main

- test/unit/test_time.py
> take timezone into consideration

- README.md
Picked a page with plenty of examples.
> Readme link update. Fixes #539

- src/compile.js
- src/misceval.js
This is an attempt to resolve #591.  I corrected all the variable names I found.  I don't know if there are any more that need to be fixed, as I'm not sure how to find them other than to carefully read all of compile.js.  Regardless, this is an improvement.
> Prefix internal names with $

- skulpt.py
- src/builtin.js
- src/dict.js
- src/function.js
- src/iterator.js
- src/lib/collections.js
- src/list.js
- src/method.js
- src/set.js
- src/str.js
- src/tuple.js
- src/type.js
- test/unit/test_builtin.py
- test/unit/test_iter.py
This provides implementations of the ```callable```, ```next```, and ```iter``` builtins.
> More builtins

- .gitignore
- skulpt.py
- src/abstract.js
- src/builtin.js
- src/compile.js
- src/import.js
- src/misceval.js
- src/object.js
- src/property.py
- support/run_template.html
- test/unit/test_decorators.py
- test/unit/test_decorators_2.py
Hi all here is the new decorators branch. But I still have a small issue. @meredydd  could you have a look at this:
```py
def decofunc(fn):
return fn
@decofunc
def func():
print "called"
func()
```
this fails because the `@decofunc` makes `func` into a suspension. And then it fails in `applyOrSuspend`.
I want to add the real tests from cpython for the property decorator.
closes #18 #426 #326
> Decorators 2

- src/builtin.js
- src/builtindict.js
- src/import.js
@rixner yeah this comment was completely wrong I copied to much there 😄
> fix comment for importBuiltinWithBody

- src/builtin.js
- src/env.js
- src/file.js
- support/run_template.html
By setting `Sk.inputfunTakesPrompt` to true, the prompt will get sent to the input function, instead of to the stdout. 
fixes #623
> make it possible to have an input fun that takes a prompt

- src/lib/turtle.js
Fixes #631.
But we should really try and figure out whats going on here. But @bnmnetp you want to ship this to runestone probably 😄.
> return .instance from ensureAnonymous

- src/lib/urllib/request/__init__.js
> make urllib use suspensions

- src/lib/turtle.js
Just removed some console logs in turtle.js
Nothing complex.
> removed unnecessary console logs

- src/set.js
Makes sure that the correct number and types of arguments are passed.
> Add type checking to set methods.

- src/lib/time.js
> Change all uses of performance to window.performance

- src/compile.js
- test/unit/test_exceptions.py
This feature has been missing for a while!
> Implement `try`/`finally`

- src/lib/turtle.js
- support/run_template.html
> skulpt function should be called with Sk.misceval.callsim

- src/builtin/sys.js
- src/file.js
- src/method.js
- test/unit/test_file.py
Thanks to @meredydd we can now have this nice thing. Also this fixes a bunch of old bugs in file.
> with open('file') ad file

- .travis.yml
- src/lib/time.js
- src/misceval.js
I finally broke and wrote this. This turns a promise into a suspension.
@meredydd I fully expect you to say I'm doing it all wrong .
> creates a suspension from a promise

- HACKING.md
Fixed typo in the HACKING.md file, it should be correct now.
> Fixed typo in HACKING.md file

- src/lib/processing.js
Stroke alpha added as per fill alpha
> Processing  - stroke alpha added

- README.md
> Doc: Adds Java to the list of requirements in "Building Skulpt" section.

- doc/index.html
Fixes: #762 
And thank you for agreeing to add this in 😄
> Added "Code the blocks" to the list of projects using Skulpt.

- src/object.js
- test/unit/test_changing_class.py
- test/unit/test_deepcopy.py
> Allow assigning to __class__ which also fixes deepcopy of instances. Issue #766

- src/lib/bisect.py
- src/lib/math.js
- test/unit/test_bisect.py
- test/unit/test_factorial.py
Previously, factorial(25) or factorial(1000) or something like that would fail. Now they work.
> Make factorial work for numbers larger than 19.

- HACKING.md
there was an extra is and my brain couldn't handle it
> Fix typo in HACKING.md

- src/compile.js
- src/import.js
- test/unit/subpackage/explicit_relative_import.py
- test/unit/subpackage/importable_module.py
Clean up `__import__`, and support explicit relative imports (eg from .. import foo).
> Support explicit relative imports

- src/misceval.js
This is a straight revert of the last commit from #839, as it broke my code (and it's a pretty small compatibility shim to carry, as was discussed in the original PR). I'm happy to have it accepted or rejected, depending on how much we decide we care about API stability.
The real question is what our attitude should be towards API-breaking changes like this. For starters, is any of the Skulpt "user API" intended to be stable? Should we keep a changelog when we make a breaking change?
I have personal opinions (yes and yes, respectively), but I see three viable policies:
1. Skulpt's API is unstable. We deliberately commit breaking changes at will, and if you use Skulpt you'd better review every PR yourself (or have 100% test coverage), else your app _will_ break.
2. The Skulpt API changes …
> Reintroduce callsim and callsimOrSuspend, to avoid gratuitously breaking users

- doc/index.html
Remove broken links, add Code Shrew
> Update the "Skulpt in the Wild" section

- src/lib/turtle.js
Add colormode function to turtle.
> Add turtle colormode function

- src/compile.js
Addresses issues #875 and #868
Already fixed in Chrome > 74
> Workaround chrome<75 optimizer delete bug

- src/lib/turtle.js
> fix the color function for arguments length

- README.md
- src/lib/processing.js
This pr contains two changes to processing module. Since they are small, I decided to make them in a single pr.
The first one is related to DOM - it removes jq dependency(this is overkill here - used only once) and removes canvas element manipulations. Direct dom changes make modern virtual dom frameworks unhappy and desyncing might lead to weird behavior. Also I think its not processing wrapper responsibility to care is element visible or exists - someone might want to use hidden element for some reasons for example.
The second change is to make default canvas size useful. Currently without size() function call it sets width and height attrs of canvas to 100. It makes little sense, since in most cases this will be different from canvas element dimensions, and that will make all …
> Processing improvements

- src/tokenize.js
Caches a few regexes in the tokeniser. I see a unit test speedup from 16-17s to 12-13s (!) locally.
Fixes #927.
> Tokenisation speed-ups

- src/enumerate.js
- test/unit3/test_enumerate.py
fix enumerate(Iterable, start=1) add add test_case 
#954
> fix enumerate(Iterable, start=1)

- src/lib/turtle.js
> Update turtle.js shape upside down problem and image turtle shape direction problem

- src/ast.js
- src/builtindict.js
- src/lib/types.py
- src/list.js
- src/misceval.js
- src/slice.js
- src/str.js
- src/tuple.js
- test/unit3/test_compare.py
A grab-bag of small fixes to improve our Python 3 fidelity.
> Small Python 3 fixes

- src/lib/turtle.js
turtle's feature.
A small change for #988 
😄
> turtle.Turtle add the shape keyword.

- src/dict.js
- src/env.js
- src/formatting.js
Give dictionary iterators Python 3 behavior and remove ```has_key``` method in Python 3.
> Dictionary iterators for Python 3.

- src/compile.js
- src/env.js
- src/set.js
- test/unit3/test_sets2.py
Also clean up set construction and iteration.
> Type checks for Python 3 in set operators.

- src/builtin.js
- src/env.js
- src/frozenset.js
- src/lib/keyword.py
- src/main.js
- src/set.js
- test/unit3/test_frozenset.py
1. Add frozenset;
2. Add `__contains__ `to set;
3. Modify lib/keyword.py,same as the Python implementation.
> Add frozenset to builtin function(Got things done!)

- src/compile.js
> Throw Python SyntaxError's, not Javascript ones.

- js/env/editor.js
These appear on Skulpt.org homepage
> Update code examples to work with Python3

- src/lib/processing.js
- src/lib/time.js
two places where we were using the wrong call signature for `assk$` and depreciated `nmber`
> remove use of deprecated nmber

- src/ast.js
- src/builtin/sys.js
- src/compile.js
- src/dict.js
- src/enumerate.js
- src/lib/collections.js
- src/lib/itertools.js
- src/lib/processing.js
- src/lib/random.js
- src/lib/string.js
- src/lib/time.js
- src/lib/token.js
- src/lib/turtle.js
- src/print.js
a selection of places where we should use `new` but don't
I also replaces `builtins` with `builtin` where appropriate
> use of keyword new

- src/builtin.js
- test/unit3/test_suspensions.py
as a complement to #1129  and #1119.
As with #1129 I will add the appropriate tests after #1119 concludes.
> make any and all suspension aware

- src/ast.js
- src/builtin.js
remove reference to `Sk.asserts.AssertionError`
and fix small type with `Sk.asserts.fail`
> small change to asserts

- src/builtindict.js
minor fix to a mistake from #1162 
It didn't show up because typeLookup checks attributes on the type and the type.prototype...
> decode should be on proto

- .github/workflows/test.yml
I think this is the line needed in the github workflows to get prs to run tests
> unittest workflow for prs

- using.md
> fix gist integration

- src/int.js
- test/unit3/test_bitwise_operators.py
Fixes #1291 incorrect right bit shift.
> Fix bitshift

- README.md
- using.md
This fixes a couple of typos, and one case where the Markdown syntax was not working due to use of HTML tags.
> Minor documentation fixes

- src/builtin.js
Helps with error propagation when using exec
> include filename in exec code if one exists

- src/ast.js
- src/compile.js
a couple of places we throw a js SyntaxError when we should throw a python SyntaxError.
> throw python syntax errors not javascript ones

- src/lib/math.js
- test/unit3/test_math.py
docs: https://docs.python.org/3/library/math.html#math.lcm
closes #1366
> feat: add lcm function to math module

- src/lib/math.js
- test/unit3/test_math.py
> Add isqrt function to math module

- src/type.js
- test/unit3/test_genericclass.py
> class getitem

- src/lib/turtle.js
> add missing global attributes to turtle

- src/descr.js
- src/property_class_static.js
- src/slotdefs.js
> More descriptor suspension awareness

- src/lib/time.js
@bnmnetp This should close #1455
> fix: time.localtime has wrong offset

- src/float.js
- src/int.js
- src/misceval.js
- src/slotdefs.js
- test/unit3/test_class.py
- test/unit3/test_float.py
- test/unit3/test_index.py
- test/unit3/test_int.py
close #1413 
tests added from cpython - i found the ones that seemed relevant with `__index__` and added them.
> Fix float and int don't support __index__

- gen/parse_tables.js
- src/pgen/parser/grammar.py
- test/unit3/test_grammar.py
Currently we get a syntax error
> fix not possible for null to be an attribute

- src/lib/re.js
- test/unit3/test_re_custom.py
Obviously the first library I wanted to use the new re module on wouldn't compile
This PR fixes the issue and adds a test case in a `test_re_custom` file
Future issues like this can be added to that file.
> Re - improve python to js regex

- CONTRIBUTING.md
Sorry for the noise... VSCode took the liberty of running prettier on the markdown file.
Just look at the section now called  "Rules for Merging PRs"
> New review process

- src/compile.js
- src/type.js
- test/unit/test_reserved_words.py
small change with a broken test
> Fix unreserve words to __set_name__

- src/function.js
- src/slotdefs.js
- test/unit3/test_skulpt_bugs.py
bug fix
small change
with test
> Fix: overriding type.__call__ can create an infinite loop

- src/ffi.js
small change, minor fix from previous PR
> ffi: Fix hooks not passed to toPy

- src/ffi.js
- test/unit3/test_skulpt_interop.py
bug fix from map/set changes
with a test
(small change)
> ffi: Fix conversion two and from map/set

- src/ffi.js
This is something I've used and copied the internal implementation
Might be better just to expose it
> ffi: add remapToJsOrWrap

- src/dict.js
- src/ffi.js
- src/lib/re.js
should be `flags` not `$flags`
and should be `sk$unacceptableBase` rather than `sk$acceptable_as_base_class`
> Fix incorrect argument to buildNativeClass

- src/lib/functools.js
- src/lib/unittest/__init__.py
- test/unit3/test_functools.py
python 3.12 removed the lock implementation of cached_property, maybe that's why it didn't get added with the initial functools implementation.
Also adds support for assertRaisesRegex in unittest
which was simple now that the re module has been updated
> functools: add cached_property implementation with tests

- src/formatting.js
- test/unit3/test_strformat.py
We leak some errors in the implementation of `str.format` that should throw python errors.
the function assumes that there will be a valid value in the args or kws
but if there isn't, we end up trying to access internal skulpt attributes of undefined
rather than throwing KeyErrors/IndexErrors
This PR fixes those errors
and adds some relevant tests from cpython
It also adds:
- support for `!a` formatter
- error when mixing between automatic and manual numbering
And I hoist out the regex from the function as a performance improvement
> fix: a couple of bugs in formatting with tests

- src/function.js
small change
fixes error message
> fix: type error message has extra quote

- src/slotdefs.js
> fix dunder iand

- src/compile.js
- src/lib/_random.js
- src/lib/random.py
- test/unit3/test_random.py
Fixes #1188 
Copied the choices method from cpyhon's random module and then put it into a new random.py file that calls all the random.js functions renamed as _random.js. 
Only works in python3
> Adds random.choices to the random module

- src/property_class_static.js
- test/unit3/test_skulpt_bugs.py
test added that demonstrates the issue
> Fix - bad arguments to tp$descr_get in class method

- src/lib/itertools.js
- test/unit3/test_itertools.py
includes tests from cpython
batched: Added in version 3.12.
pairwise: Added in version 3.10.
> Add itertools.batched and itertools.pairwise

- src/builtin/sys.js
- src/file.js
- src/lib/logging/__init__.py
- test/unit3/test_logging.py
Adds logging support
mostly from the cpython library with some adaptions to skulpt
Not supported:
- String templates style support
- No error checking in string format style
- No error handling support
- No warning support
- No file handler support
- no logging.config module or logging.handlers module
adds sys.stderr - which is the same as sys.stdout
> Logging.py

- src/str.js
amendment to #1481 
Seems sensible to do some interning of strings
so that some `is` operations follow cPython
This PR implements caching of the empty string and single ascii characters
Things like this work in cPython
```python
>>> x = "f"; y = x + "oo";
>>> x is y[0]
True
>>> x = chr(256); y = x + "oo";
>>> x is y[0]
False
>>> x = chr(255); y = x + "oo";
>>> x is y[0]
True
```
> str: implement interning of small strings

- src/env.js
- src/misceval.js
allow suspensionHandlers to have a configurable default implementation
> Add default suspension handlers configurable in Sk.configure

- src/abstract.js
- src/ffi.js
- test/unit3/test_skulpt_interop.py
> Ensure we check the value is true when doing ffi.toPy
