HACKING.rst
src/builtin.js
src/compile.js
src/errors.js
src/str.js
test/run/t523.py.real
test/run/t523.py.real.force

Replace the global Sk.curr{LineNo,ColNo,Filename} with local vars in each stack frame, allowing us to generate proper stack traces for exceptions.
This required modifying one test, as it relied on exceptions reporting incorrect line numbers.
This PR merges nicely with PR #324, and they can be applied in either order.

Provide stack traces for exceptions

---

src/misceval.js
src/type.js
test/run/t520.py.real
test/run/t520.py.real.force

Targets #97:
- ```Sk.misceval.buildClass``` now passes python objects to ```Sk.builtin.type```
- ```Sk.builtin.type``` now checks for arguments and unpacks
- Adds ```__module__``` if not set
Currently a ```t520``` fails due to another returned hash value - I am not sure why.

Fixes type() by passing in real python objects

---

src/lib/turtle/__init__.js

Makes the turtle DOM target focusable so that it can capture key events
Updates the key listeners to listen on the configured DOM target instead of the window
fixes #353

Restrict key events to turtle canvas

---

src/lib/turtle/__init__.js

calling turtle.circle with the steps argument should create a polygon that fills
a circle of the radius specified.  This PR fixes the length calculation to appropriately
size the sides of the polygon.

Fixes turtle.circle() when steps != None

---

src/compile.js

The retainglobals flag seems to have been broken by the introduction of suspensions. Before the breaking commit, $loc was being assigned to $gbl AFTER Sk.retainGlobals was checked and Sk.globals was applied. After the commit, this assignment no longer took place and $loc remained as an empty object. This commit simply adds the assignment of $loc back in the case of Sk.retainGlobals being true.

Reassign $loc to $gbl if retainGlobals flag is set

---

src/lib/processing/__init__.js

1. processing.width and processing.height are now ints;
removed width() and height() functions
2. processing.size() had the arguments misnamed/switched:
processing.size(w, h)

This PR fixes two Processing issues with width and height

---

skulpt.py
src/lib/unittest/__init__.py

unittest now just counts each test function rather than every assert.  It will also report the name of the function when a test fails.  -- this may be brittle as skulpt does not support the ``__name__`` attribute on function objects.

fix counting method for tests

---

README.md

A minor update to the project's Readme so new developers can find our coordination issue.
I left the ideas list underneath untouched even though there is some duplication with open issues and tasks on #400. That's a great exposition of the different projects and interested devs can click thru to claim a task.

Readme refresh & link to coordination issue

---

src/compile.js
src/misceval.js

Property checks are approximately twice as fast as instanceof checks
(http://jsperf.com/instanceof-performance/23).

Use a property to check if a value is a Suspension

---

src/compile.js
src/env.js
src/errors.js
src/lib/unittest/__init__.py
test/test.js
test/unit/exiting_module.py
test/unit/test_exit.py

Previously, `SystemExit` exceptions were being caught at the module level,
presumably to not crash an interpreter which did not expect this
exception. However, this had several problems:
1. Importing a module which calls `exit()` in its body would not
correctly exit the importing module.
2. The additional `try`-`catch` logic required for the special treatment
of `SystemExit` had a noticeable performance penalty.
3. Special casing `SystemExit` on a module level is inconsistent with
Python's behaviour, which treats it like any other exception, and
where it is up to the interpreter (not the module) to catch this
exception and deal with it as desired.
4. Additionally, `SystemExit` was incorrectly set to inherit from
`Exception` (instead of `BaseException`), which meant that except
blocks …

Removes special treatment of SystemExit

---

src/errors.js

Make ExternalError happy to be fed an Sk.builtin.str(). Among other things, this makes it produce nice output when constructed in Python

Allow ExternalError to be instantiated from Python

---

src/lib/collections.py

This should have been removed in #411.

Remove not implemented placeholder collections module.

---

src/dict.js
src/lib/collections/__init__.js
src/lib/unittest/__init__.py
test/unit/test_ordereddict.py

This adds the ```OrderedDict``` type to collections.
I probably will not add ```deque``` and ```namedtuple``` any time soon, so others should feel free to go after those.
Trying to run the CPython tests exposes that our ```dict``` implementation is missing a lot of features that are probably not as commonly used as the core we have implemented.

Implementation of OrderedDict

---

src/dict.js

Pretty self explanatory.
We are missing the following methods (assuming #423 is accepted, which implements ```clear``` and ```setdefault```):
* ```copy```
* ```fromkeys```
* ```iteritems```
* ```iterkeys```
* ```itervalues```
* ```popitem```
* ```update```
* ```viewitems``` (2.7)
* ```viewkeys``` (2.7)
* ```viewvalues``` (2.7)

Throw NotImplementedError for unimplemented dictionary methods.

---

skulpt.py

OK, this is pretty simple, and should be accepted quickly as this plugs a hole in the new unittests.
By not checking the returncode of the subprocess we miss out on the fact that sometimes we get an error just loading up the code for a particular unittest which goes uncounted as a failure.  
If the test file exists then it better work or should cause the tests to fail.  I caught this in my own code a few days ago, and then I saw the problem again looking at @waywaaard's complex branch:
```
test/unit/test_complex.py
src/float.js:128: TypeError: a float is required at <unknown>
throw new Sk.builtin.TypeError("a float is required");
```
This did not count as a fail and wrongly made it look like all unittests had passed.

Check return code on rununits subprocesses

---

src/lib/unittest/__init__.py

@eah13 uncovered a bug in unittest where assertAlmostEqual and NotAlmostEqual were missing the optional parameter for the number of places to compare.

missing parameter on assertAlmostEqual and NotAlmostEqual

---

doc/static/repl.js
repl/repl.js

Still behaviors in the repl that don't match Python's but this small fix will avoid a nasty error for a common behavior: pressing return on an empty prompt.

Continue in while loop if return is pressed

---

.gitattributes

Marks test files as non-text in .gitattributes, to prevent line-ending
normalisation on them when checked out on Windows with autocrlf enabled.
Also, mark all .py files as lf-only, as this is what the parser expects (in
particular, for triple quoted strings).

Add .gitattributes for test outputs

---

skulpt.py

This is needed for some cloud IDEs and other dev setups with limited port access.  Does not alter behavior of `./m host` - but if there are arguments will take the first argument and pass it to the server to override the default port.  Catches errors from non-integer inputs.  Updated the usageString too.
Another contender for tiniest pull request evar.

Made skulpt.py host port customizable (default left at 20710)

---

skulpt.py

I saw a rogue tmp.js file on the dist repo. This makes sure it won’t be added again.

remove tmp.js after using it

---

src/abstract.js
src/compile.js
test/unit/test_unpack.py

Use iteration at run time to unpack sequences to match CPython's behavior.
This does not currently work with user-defined classes that support iteration (#469).  However, if the solution to that preserves the internal iteration interface, then they should just work once that is resolved.  Those tests from CPython are in the ```test_unpack.py``` file, but are commented out.
Resolves #430

Unpack sequences

---

skulpt.py
support/run_template.html

I suspect this is a workflow that many of us follow but is usually a pain.  So often I put up with the crappy command line debugger and waste time because its too much of a pain to make yet another test webpage.  So I fixed that.   Introducing `./skulpt.py brun myfile.py`
Did a wee bit of refactoring in skulpt.py to make the `brun` command.  It works just like `run` except it generates a simple webpage so you can run in the browser nearly as fast as running on the command line.  But without all the hassle and manual copying of files.
1. build an uncompressed skulpt.js  (no waiting for dist to complete)
2. build skulpt-stdlib.js
3. grab the file from the command line and throw it into a webpage template
4. open said page in browser (I don't know how to do this in Windows @albertjan) …

add brun command to run a file in the browser

---

src/env.js
src/lib/processing.js
src/lib/turtle.js

Any event driven skulpt callbacks can result in uncaught exceptions.
This PR adds the ability to specify an uncaughtException handler when setting up Skulpt
which will allow the implementer to surface those errors to the end user.
This method must be called explicitly in whatever js library is generating the suspensions.
See the changes in turtle.js of this PR for an example of how it can be used.
```python
import turtle
def click():
pass
s = turtle.Screen()
t = turtle.Turtle()
t.shape('turtle')
s.onclick(click)
```
If the page implementer specifies an Sk.uncaughtException handler,
the error thrown in the above example will be sent to the handler.
Fixes #455

Add optional uncaughtException handler to Sk.configure

---

skulpt.py

The sun comes up very early in Prague this time of year :smile:
This fixes the problem of checking for the existence of gzip.  Should work on all platforms now and get the dist command back to a fully working state.

fix broken dist command

---

src/abstract.js
src/builtin.js
src/builtindict.js
src/constants.js
src/dict.js
src/errors.js
src/float.js
src/import.js
src/int.js
src/lib/collections.js
src/list.js
src/long.js
src/misceval.js
src/numtype.js
src/object.js
src/seqtype.js
src/set.js
src/str.js
src/type.js
test/run/t407.py.real
test/run/t407.py.real.force
test/run/t520.py
test/run/t520.py.real
test/run/t520.py.real.force
test/unit/test_subclass.py

This is the last PR related to #481, and makes builtin types subclassable.
Here's a brief overview of what this PR makes possible. See [test_subclass.py](https://github.com/mchat/skulpt/blob/subclass/test/unit/test_subclass.py) for more comprehensive testing.
```python
class SimpleInt(int): pass
x = SimpleInt(10)
print x == 10           # True  (int.__eq__)
print x + 10            # 20    (int.__add__)
print x - 10            # 0     (int.__sub__)
class MyInt(int):
def __add__(self, other):
return 5
x = MyInt(10)
print x == 10           # True  (int.__eq__)
print x + 10            # 5     (MyInt.__add__)
print x - 10            # 0     (int.__sub__)
class AnotherInt(MyInt):
def __sub__(self, other):
return -5
x = AnotherInt(10)
print x == 10           # True  (int.__eq__)
print x + 10 …
```

Make builtins subclassable

---

src/int.js

In all of @mchat 's great work we lost the check for the python3 flag for the regular / operator.  I realize some may think that was a good thing, but it breaks a bunch of examples in my books.

check for python3 flag to get python3 division

---

src/builtin.js
src/misceval.js
src/object.js
src/type.js

A few improvements to performance in Skulpt, mostly dealing with avoiding lookup methods unless absolutely necessary.
Sk.misceval.richCompareBool now checks for the existence of a Skulpt "shortcut" method (i.e. "ob$eq" for equality) before calling expensive lookup functions.
In Sk.builtin.type.prototype.tp$getattr, an expensive type lookup is now only performed if it is needed.

Performance tweaks

---

src/compile.js

These were global variables.  At a minimum, this causes problems when there is an exception thrown by an imported module. The traceback will be corrupted, as the line and column numbers will all be the same, since all modules were sharing the same variables.

Make $ret, currLineNo, and currColNo local variables.

---

m
package.json

`package.json` was demanding a version of `jscs` that barfed on the codebase, and didn't demand `jsdoc` at all. Presumably everyone else so far has been using globally-installed versions!
These commits update those dependencies, and make `m` (which used to be a symlink) a bash script that runs `skulpt.py` with a `$PATH` that makes sure we invoke `jshint` from our own dependencies rather than whatever's installed globally.

Update NPM dependencies

---

src/dict.js

Sk.remapToJs(Sk.remapToPy({hello:"world"})) was failing on properties with a $hash but not items.  I added an explicit check and now it works.  Happy to add a test to go with it if you show me where the javascript only tests go.

remapToJS() wasnt working for Dicts 

---

src/lib/turtle.js

Looking to resolve #409 I have a working turtle.clone() method, but with one problem that I can see. It loads the turtle module using Sk.misceval.loadname using the Sk.globals object, so if the user writes 'import turtle' in a function then this method will not be able to find it.
Also, I'm not totally sure if the new clone turtle instance has the write Turtle type according to skulpt.
But this is a start

Turtle clone works, still has some issues

---

src/builtin/sys.js

when you call sys.debug from the repl it fails because it returns `undefined` @spaceone reported this. In #283.

return None from sys.debug

---

src/int.js
test/unit/test_int.py

This PR fixes the #513. Instead of using the javascript calculation I've used "python" methods for calculating. Those ensure the correct handling of the types and throw appropriate errors.

Fixes integer modulo for zero divisions

---

src/builtin.js
test/unit/test_builtin.py

Fixes `abs` for calling `__abs__` on user defined classes.
```python
class TestAbs:
def __init__(self):
self.foo = -3
def __abs__(self):
return -self.foo
bar = TestAbs()
print abs(bar)
```

Fixes abs builtin for User Defined Classes

---

src/lib/urllib/request/__init__.js

The Python spec says urlopen issues a POST request in case the data parameter is set. (https://docs.python.org/3.0/library/urllib.request.html)
This PR adds a simple check for that and changes the request type to POST and sends the data as the request body.

Adds POST request to urllib.request.urlopen(..)

---

src/str.js
test/unit/test_strcount.py

str.count('.') now first escapes all the special regex characters.

Fix issue #536

---

src/lib/processing.js

When using the processing module, processing instances keep running across subsequent Skulpt runs if it's not explicitly stopped. This is best seen with an example.
Try pasting the code below into the editor over at: http://www.skulpt.org/static/proctest.html
Click Run several times and you'll notice that the ball starts moving quicker and quicker with each run. At first I thought it was a frameRate issue but determined that the Processing instance was still running. From [Processing](http://processingjs.org/learning/): "The draw function loops continuously unless you tell it otherwise by using the exit() command." I think another draw function is started each time Run.  
```python
from processing import *
import math
def setup():
size(203, 500)
frameRate(60)
global position
position = …
```

Stop Processing instance (if it exists) on subsequent runs.

---

src/import.js

Should fix #299 .
Example:
```python
from unittest import gui as mystuff
print("nothing to see here")
print(dir(mystuff))
```

Fixes imports that are own files but show up in the from list

---

src/lib/turtle.js

Without this patch some turtle methods accept only unnamed keywords arguments. For example, this works:
`turtle.Screen().setup(400, 400)`
but this fails with the error `got an unexpected keyword argument`:
`turtle.Screen().setup(width=400, height=400)`
Fixes #483

Add keyword arg names for some turtle methods

---

src/lib/random.js
test/unit/test_random.py

This differs somewhat from CPython. The CPython implementation consists of two paths: a general algorithm and an optimized path for the case when k is much smaller than len(population). This pull request implements only the general case (runtime proportional to len(population) but no extra space is required). An optimized case could be implemented later, but I think it is more important to have a working version even if it is slow on large populations.

Implement random.sample()

---

src/misceval.js

There is currently no easy way, from Javascript, to catch an exception from a Python function that suspends. `Sk.misceval.tryCatch()` fixes this. It calls a function that may return a suspension, and catches any exceptions thrown directly by that function or when resuming any suspension it returns.

Add Sk.misceval.tryCatch()

---

src/sorted.js
test/unit/test_list.py

Fixes #459.
The issue is that currently, calling sorted([2, 3, 1], reverse=False) returns [3, 2, 1] (same as sorted([2, 3, 1], reverse=True). This is my first time contributing, please let me know anything I can do to make this more correct. Thanks!

Unpack reverse before comparison for sorted()

---

package.json

This package.json modification are to used to load the current source code over npm directly from github.
Because of the "private": "true" flag it will not be uploaded the to the npm repository.

Update packeage.json to be compatible with npm.

---

src/builtin.js
test/unit/test_StringIO.py

This fixes a bug in the new implementation of `raw_input` that would break if no prompt was given.

Fix bug in input

---

src/dict.js
test/unit/test_dict.py

It was getting an unpleasant `AssertionError`, rather than the correct `AttributeError`. Fix it by remapping arguments correctly.
Also added my first new-style unit test for it (they're nice! Yes, I'm behind the times :-P)

Prevent dict.__getattr__() from exploding

---

src/lib/processing.js

The `PVector::normalize` method was referencing an undefined variable and throwing an error any time it was called.

Fixes call to the PVector::normalize method in processing.

---

src/ffi.js

JS bools were not being turned into `Sk.builtin.bool`s. This patch fixes that.

Remap bools correctly in Sk.ffi.remapToPy()

---

src/misceval.js

Realising the `arguments` makes the V8 optimiser bail out. While this isn't the most glaring performance bottleneck in Skulpt, it was contributing to some performance issues in Anvil.

Improve optimisability of Sk.misceval.chain()

---

skulpt.py
src/abstract.js
src/compile.js
src/misceval.js
test/unit/test_contains.py

This PR makes it possible to use the `in` operator over suspendable generators.
It also introduces the `iterFor` function, which makes loops over suspending iterators a much more pleasant experience.
Testing it also required allowing unit tests to suspend.

Make the `in` operation suspendable

---

src/lib/processing.js

Processing's `fill` and `colorMode` didn't have full support for alpha and RGB/HSB.

For processing: Adds alpha arg to fill and green, blue, alpha args to colorMode

---

src/abstract.js
src/builtindict.js
src/compile.js
src/errors.js
src/type.js
test/unit/test_iter.py

`raise StopIteration` used to be a horrible hack; it is now an exception (as in Python) that is caught in the shim code between `tp$iternext` and user code.
Also makes `next()` suspendable (but not `__iter__`, yet)

Make custom iterators suspendable, and fix StopIteration

---

src/function.js
src/method.js
src/misceval.js
test/unit/test_calling.py

Also removes the copy-and-pasted code between `method` and `func` - a method call just sticks `self` onto the beginning of its arguments and then calls the underlying function.

Support keyword arguments properly

---

src/tuple.js
test/unit/test_calling.py

The recently added test_calling.py fails when called from CPython.  The problem is that ```*args``` is a tuple, but the assertions were expecting a list.  I think this highlights that we should run the unittests through CPython in travis so that we can test the tests, so to speak, before we merge them.
Fixing the tests exposed a bug.  The bugfix is simple, as we were not properly checking if we were comparing to a different type in the tuple ```tp$richcompare``` function.

Fix tuple comparison to other types and fix failing tests.

---

test/unit/test_random.py

This test keeps failing the build, but not always, I'm not really comfortable with the random maths.
@waywaaard Do you have any idea why it doesn't always give the correct result?
I suggest we merge this and disable the test until we have a solution.

disable failing random test

---

src/env.js
src/lib/time.js
src/misceval.js

This adds some infrastructure to allow the problem in #560 to be addressed.  Currently, if you want to reset Skulpt, you have to do so externally in the code that is driving Skulpt.  This PR allows that external code visibility to see any pending timers.  If you don't change anything, it defaults to behaving as it does now.  But, if you set ```setTimeout``` in the call to ```Sk.configure```, you can manage the timers.
The demo infrastructure doesn't have any sort of "reset" button, so here's a simple example of how one might use this:
```
var timers = [];
var timeout = function (func, delay) {
var id;
var wrapper = function () {
var idx = timers.indexOf(id);
if (idx > -1) {
timers.splice(idx, 1);
}
func();
};
id = setTimeout(wrapper, delay);
timers.push(id);
};
var clear_timeouts = …
```

Add infrastructure to allow Skulpt to be reset.

---

src/compile.js
src/misceval.js
src/object.js
test/unit/test_decorators.py

This takes the work from the decorators branch, and gets it cleanly up to date with master.  I propose that we focus on getting the descriptor part to work in this PR, which I think is pretty close.  Then make a second PR when we are ready to get decorators fully working.
The great thing about this branch is that @waywaaard 's python only implementation of property works!  I would really like to get that into a builtin because I'm looking at some changes to the book where I would use properties.

Descriptors

---

src/env.js

Fix ```Illegal Invocation``` error introduced by #579.  Most (all?) browsers need ```setTimeout``` to run within the global context.

Run setTimeout within the global context.

---

src/import.js
test/unit/test_import.py

See issue #583 
With the fix both ways are working:
```python
from unittest.gui import TestCaseGui
```
and
```python
from unittest import gui as mystuff
```
I've added two unit tests, so that we do not break those again in future.

Fixes #583 Broken Import for dotted names in from list

---

src/ffi.js

Currently, `remapToPy()` turns `null` into an empty dictionary (because `typeof (null) == "object"`). Make it map to `None` instead.

remapToPy() maps null to 'None' rather than '{}'

---

src/import.js
src/lib/test/test_support.py
src/lib/unittest/__init__.py
test/unit/test_index.py

Updates to allow more unittest files to pass in CPython.
This one requires some thought.  I am not sure that the change to import.js is correct.  It doesn't break any of the other tests, but I'm not sure if the change should be here or if ```Sk.importModuleInternal_``` should be returning something different.  So, I'd like to have multiple people look this over and think about it.
There were attempts to get importing test_support working in #310 and #450, but they are out of date at this point, so I could not just use that solution, but it may be instructive for others to look at those ideas.
(Incidentally, I also uncommented some tests in test_index.py that now pass because we have implemented more features!)

Use test.test_support to be compatible with CPython.

---

src/builtin.js
src/misceval.js
src/type.js
test/run/t376.py.real
test/run/t376.py.real.force

There are many implicit calls (to functions like `__len__`) triggered from internal 'dunder-named' function calls (like `tp$length`). This PR starts the work of normalising those calls - it uses `Sk.abstr.gattr()` to get the attributes (so they can be dynamically returned by `__getattr__` and friends), and makes some (such as `__call__` and `__len__`) suspendable.

Normalise implicit calls

---

src/compile.js
test/unit/test_subclass.py

We were using JS `instanceof` in exception-type testing. The real Python `isinstance` now works fine, and supports syntax like catching tuples of exception types. This PR makes us use it.

Support catching multiple types of exceptions in an 'except' block

---

src/dict.js
src/misceval.js
src/object.js
src/set.js

Trying to be a bit more compiler/v8 friendly. Timed in a browser with @rixner's [script](https://gist.github.com/rixner/f79dfa52a0385e5c82d147ae3d06c50c), modified to time each `update()` call separately instead of all of them together, and to aggregate these timings.
Timings before:
```
min time: 0.0622251033783
average time: 0.0676951956749
stddev: 0.00581978406985
```
Timings after:
```
min time: 0.0563948154449
average time: 0.0603578090668
stddev: 0.00456230040262
```

Minor v8 speedups

---

src/errors.js
src/parser.js
src/tokenize.js

One for discussion, I think!
Some user testing recently revealed that people were left scratching their heads over `ParseError`. It doesn't Google well, because Python calls it a `SyntaxError` instead. This PR proposes to rename it to `SyntaxError` to match other Python implementations.

Rename ParseError to SyntaxError

---

src/compile.js

Otherwise we can attempt to save temporaries from now-eliminated dead code,
and we get "no such variable X" errors.
Repro case:
```python
import time
time.sleep(0.01)
for p in []:
break
for n in []:
pass
```
The inner loop (`for n in []`...) is dead code, so it is not included in the compiled output, but the suspension code still tries to save its temporaries (which are now undeclared). This is the straightforward fix that forces the declaration of all saved temporaries.
Long-term, we need to improve our temporary/variable lifetimes, probably by reifying them into heap objects that can survive an exception (#295 and friends), but that shouldn't stop us fixing a bug like this.

Bugfix: Explicitly (re)declare all suspendable temporary variables

---

src/compile.js

This should provide a more universal fix to the problem identified in #606 
@rixner, @DIJamner for review please

Wrap compiler output in a function to avoid scope gensyms colliding

---

src/builtin.js
src/builtindict.js
src/function.js
src/lib/copy.py
src/lib/types.py
src/method.js
src/object.js
src/type.js
test/unit/test_copy.py
test/unit/test_deepcopy.py

This is an implementation of the ```copy``` and ```types``` modules.  They are taken directly from CPython with minor modifications (and things commented out that Skulpt doesn't yet support).  There are also internal Skulpt updates to support the features the ```copy``` module requires, including the ```id``` builtin.
I'm not sure if we have already established the proper way to cite code from CPython.  Please speak up if you believe the copyright notices at the top of the relevant files are insufficient (or should be handled differently).  It does seem like perhaps the LICENSE file at least needs to be updated (regardless of anything to do with this pull request).

Copy module

---

src/classmethod.py
src/compile.js
src/function.js
test/unit/test_decorators.py

Same deal as for the staticmethod except this one does not work.  It is exposing some strange closure bug that needs someone smarter than me to track down.
running the unit tests will reveal:
```
Ran 1 tests, passed: 1 failed: 0
Test threw exception in  TestDecorators.test_classmethods  (ExternalError: TypeError: Cannot read property 'tp$name' of undefined on line 11)
Ran 3 tests, passed: 2 failed: 1
```
The line 11 in question is line 11 in classmethod.py
Any ideas???

classmethod

---

skulpt.py

20d27cce65da744d9d810ff7be34ce8785d7fa59 broke the `./m brun` command, by requiring a `root` substitution in `run_template.html`. This patch fixes it by adding a trivial `root=""`.

Fix `brun` command

---

src/builtin.js
src/type.js
test/unit/test_bug619.py

I know it's absolutely ridiculous, but you brought it up @meredydd. 
This didn't work:
```py
import time
class Test():
def __len__(self):
time.sleep(1)
return 42
t = Test()
print len(t)
```
This PR fixes that 😄 Although I don't know if this is correct.

Sleepy __len__.

---

repl/repl.js

i had issues with lines starting with #-sign, so i figured out, how to add an additional regexp test. "^#.*" did the trick.

error in repl.js with comments

---

src/abstract.js
test/unit/test_binop.py

This is a fix for issue #465. It's a more general solution than PR #492, that lets us re-use the existing bin-op infrastructure (including `__radd__` and similar complexities). Tests included.

Make in-place operations fall back to normal binary ops

---

src/function.js
test/unit/test_calling.py

When a Skulpt function has free variables, it takes an extra argument (the parent's `$cell`) to look them up in.
Unfortunately, we were adding that extra argument *before* we matched keyword arguments with named arguments, which was leading to odd errors. This PR produces the correct behaviour, by adding the closure argument after keyword matching has been performed. Test included.

Make closures work with keyword argument matching

---

src/abstract.js
src/type.js
test/run/t551.py

They never had any business being in the global `Sk.abstr.gattr()` (or `sattr`) function in the first place. Their presence was causing errors accessing any class attribute of a class with `__setattr__`, or any new-style class (which inherits a `__setattr__` from `object`). This is one of those "I can't believe it lasted that long" bugs.

Move `__getattr__` and friends into instance `tp$getattr()` and friends

---

src/abstract.js
src/function.js
src/misceval.js
src/object.js
src/type.js
test/run/t407.py.real
test/run/t407.py.real.force
test/run/t551.py
test/unit/test_constructors.py
test/unit/test_int.py

This PR supports the `__new__` method when constructing objects.
In order to make the tests pass, I also had to clean up our support for static/class methods and hand-rolled Python descriptors (I've made them use the proper descriptor system, which was already in use for methods, and removed the extraneous checks in function invocation).
This PR depends upon #634 because it also touches the attribute-lookup mechanism.

Support `__new__` in object construction

---

src/abstract.js
src/function.js
src/lib/datetime.py
src/misceval.js
src/object.js
src/type.js
test/run/t407.py.real
test/run/t407.py.real.force
test/run/t551.py
test/unit/test_constructors.py
test/unit/test_int.py

Once PRs #635 and #634 are applied, Skulpt can load and apparently run the `datetime` module from PyPy 5.1.0 (the only thing I had to take out was the pickle support, which used `struct`).
Obviously those older PRs should be reviewed first.

Add `datetime` module

---

src/type.js

tl;dr Fix "this object is not callable"/"not iterable" error messages.
This mostly reverses commit ae9fed464, which tried to accommodate dynamically provided dunder-functions by using Sk.abstr.gattr(). The correct fix (implemented in commit 2e43d47 / PR #634) was to make tp$getattr() do dynamic lookup properly. Using Sk.abstr.gattr() just made things complicated, and in particular made `__call__`/`__iter__` lookup failures come out as generic AttributeErrors rather than TypeErrors with helpful messages.
Reversing this means that we get better error messages (like "this object is not callable/iterable") again.

Make dunder lookup use tp$getattr() again. Gives us better error messages.

---

package.json

Non of the dependencies are actually needed at runtime

Change dependencies to devDependencies

---

.travis.yml
CONTRIBUTING.md
HACKING.md
README.md
dist-update.sh
package.json
test/unit/test_list_sort.py

Fixes #558.
* Removes the recommendation to `npm install -g`
* Adds npm scripts for the following commands:
```
testdebug, regengooglocs, regensymtabtests, rununits, vmwareregr, regenparser, regenasttests, regenruntests, upload, doctest, doc, browser, debugbrowser, vfs, host, repl, test
```
* `npm run build` runs `./skulpt.py dist`
**Warning**: Passing parameters directly to `npm` scripts doesn’t work. Instead, use `--` and then pass the options.

Add npm scripts

---

src/builtin.js
src/compile.js
src/misceval.js
src/object.js
test/unit/test_reserved_words.py

Use the same reserved words mangler for `get/setattr` as the compiler uses. So we can use `get/setattr` to get fields like `default` and `delete` from objects.

fix reserved words in get and set attr

---

src/errors.js
test/unit/test_subclass.py

The `args` attribute was missing from exceptions. This change adds it.
It works by adding an `args` descriptor that exposes the javascript `args` property (which is already a python tuple). I could also have overridden `__getattr__`; I thought this was cleaner.

Add `args` attribute to standard exceptions

---

.gitignore
.travis.yml
src/lib/turtle.js

turtle.js args.length check missing the a `.length` thus can't throw an error on args missing

fix args.length check, add tmp.js to .gitignore

---

src/list.js
test/unit/test_list.py

We didn't have explicit dunder-functions (eg `__setitem__`/`__getitem__`) for the list class. This made subclassing it a pain. Now we do.

Implement explicit dunder-functions in list class

---

skulpt.py
src/lib/platform.js
support/run_template.html

This pull request adds a rudimentary platform module.  Perhaps most interestingly ```platform.python_implementation()``` returns ```"Skulpt"```, allowing you to check if you are running in Skulpt or another interpreter.
Also, a ```brun3``` command is added to skulpt.py to run Python 3 in the browser.
The Python versions are arbitrarily set to 2.7.0 and 3.2.0 for ```platform.version()```.  Not sure if those are the best values or not.

Platform Module

---

src/builtin.js
src/file.js
test/unit/test_input.py

When you return a value from the reject handler of a promise the resulting promise is `resolved` not `rejected`. 
These changes make sure you can reject your `Sk.input` promise implementation.

handle promise in suspension correctly, use internal suspension data to resume

---

src/ast.js
src/compile.js
src/errors.js
test/unit/test_exceptions.py
test/unit/test_with.py

This PR supports the `with` statement (PEP 343) in Skulpt. Context managers ahoy!
Many thanks to @albertjan for the parser patch that made this possible.
(This PR builds on my #680 `try`/`finally` implementation, as `with` uses many of the same mechanisms)

Implement the `with` statement

---

src/dict.js
test/unit/test_dict.py

This change supports supplying keyword arguments to the `dict()` constructor.
By defining a `tp$call` slot on the `Sk.builtin.dict()` function, I could separate out the Python and JS call paths, and add kwarg handling neatly.

Support constructing a dict with kwargs

---

src/abstract.js
src/builtin.js
src/dict.js
src/enumerate.js
src/env.js
src/float.js
src/generator.js
src/import.js
src/int.js
src/iterator.js
src/list.js
src/long.js
src/number.js
src/object.js
src/set.js
src/str.js
src/tuple.js
src/type.js
test/run/t376.py.real
test/run/t376.py.real.force
test/run/t407.py.real
test/run/t407.py.real.force
test/unit3/test_builtin.py
test/unit3/test_call.py
test/unit3/test_dict.py
test/unit3/test_int.py
test/unit3/test_list.py
test/unit3/test_set.py

This pull request incorporates fixes for Python 3 in various places.
The builtins oct, pow, len, round, and format are updated.
There are fixes/improvements to ```__contains__``` and ```__format__```.
There is also some infrastructure added to switch method names between Python 2 and Python 3.

Various Python 3 updates

---

src/lib/time.js

This PR fixes the issue with `time.mktime` described in #713.

Initialise JS Date correctly in time.mktime. Fixes #713.

---

.travis.yml
skulpt.py
src/file.js
src/set.js

At some point in the past `jscs` and `jshint` weren't called with the correct args anymore, and because we don't globally install jscs and jshint anymore, the script broke. This PR addresses these things and fixes the collected lint over time.

remove calls to jscs and jshint in travis.yml

---

src/builtin.js
src/dict.js
src/import.js
src/object.js
src/type.js
test/run/t407.py.real
test/run/t407.py.real.force
test/unit/test_attrs.py
test/unit/test_decorators.py
test/unit/test_inheritance.py

`@property` is great, but it currently breaks if the getter or setter function suspends. This PR fixes that:
* It compiles python builtins with `canSuspend` set to true, so that the compiled code from `property.py` supports suspensions.
* It fixes some `canSuspend` plumbing to make suspending descriptor setters work
* (This branch is on top of #708, which already makes suspending descriptor getters work)

Support suspending in property getters and setters

---

src/builtin.js
src/dict.js
src/object.js
src/type.js
test/run/t407.py.real
test/run/t407.py.real.force
test/unit/test_attrs.py
test/unit/test_inheritance.py

Skulpt's implementation of `object.__getattr__` was incorrect (`object.__getattr__` does not exist in CPython).
In CPython, `object.__getattribute__` is the default implementation of the "get attribute" slot (`tp$getattr` in Skulpt), and it falls back to `__getattr__` if it doesn't find anything. I have updated the Skulpt implementation to do the same thing.
This means that the `type.js` implementation of `tp$getattr` just got a whole lot simpler - and we can actually use `object.__getattribute__` from Python code now.
In addition, `object.__getattribute__` now actually throws an `AttributeError` instead of returning `undefined` (which is not a legal Python value, and confuses the heck out of calling code) - which was the original bug that prompted this change. The yak hair is piled deep …

Implement object.__getattribute__; tidy up attribute getting

---

src/lib/time.js

It now defaults to UTC if there's no timezone in the browser's default string representation, which will be an unpleasant surprise but beats an ExternalError and is probably a sensible default.

Prevent time.js exploding if no timezone available

---

src/module.js

Previously:
import sys
sys.fooo
AttributeError: '<invalid type>' object has no attribute 'fooo'
Now:
AttributeError: 'module' object has no attribute 'fooo'

Allow modules to report their type as "module" properly.

---

repl/repl.js

In the REPL there is a bug with single-line expressions that throw an exception:
```
>>> fjeiosjfoesjfoes
NameError: name 'fjeiosjfoesjfoes' is not defined on line 1
1>: evaluationresult = fjeiosjfoesjfoes
2 : if not evaluationresult == None: print repr(evaluationresult)
>>> 
```
What is all of that evaluationresult stuff? The repl inserts it into your code and then doesn't remove it before showing you your code again. This small patch does that.

Repl exception reporting

---

src/builtin.js

@prescod have a play with this see if this works for you.
`jseval("5")` will return `5`
and
`jseval("window.alert('test')")` also still works and returns `None`
and 
`jseval("throw new Error('testing!');")` also still "works"

spruce up jseval

---

skulpt.py

[https://pythonhosted.org/GitPython/0.3.1/intro.html#getting-started](url)
that's a dead link to GitPython
[https://gitpython.readthedocs.io/en/stable/intro.html](url)
this is the new one.

changed a dead link

---

src/object.js
test/run/t407.py.real

@meredydd you were right, `__get__` doesn't belong on object and wasn't used at all.

remove unused __get__ on object

---

src/lib/image.js

Although image is not a part of the stdlib for python this one has been a part of skulpt-stdlib for many years.
There is a larger question of how we should distribute / publish 3rd party libraries that people would typically install with pip.  Especially now that the External stuff is gone with the latest merge back from trinket.

merge Runestone fixes to image.js

---

src/ffi.js
src/formatting.js
src/misceval.js
test/unit/test_strformat.py

This addresses #834 but I'm not sure it's the best solution.  The string formatting code is fast and loose with Python vs. Javascript types, making it a bit messy.  I think I did manage to fix the reported bug (and a few related bugs) without breaking anything else, though.  But I'm not happy with the back and forth conversions that were needed.
This would benefit from others running more code through it before accepting it, though, to make sure that I did not introduce any regressions that are not captured by the somewhat limited test suite.

Fix string formatting

---

src/lib/turtle.js

This was originally to fix #849 
It seems that in the current system arguments.length is not 0 if no arguments are passed.  When pencolor is called with no arguments, arguments.length is 5 
This seems a more reliable way of dealing with it and should fix the call with no args across the board.

Bug fix for determining if 0 args

---

src/int.js
test/unit3/test_int.py

Add some simple checks to determine if add/subtract result overflows integers and use long add/subtract when it does.  This fix was so simple, I'm not sure why we didn't do it long ago...
I ran a simple performance test, and using d8, I see about a 2% overhead to doing these checks on a long running while loop that does nothing but add/subtract numbers that don't overflow.
Fixes: #729

Check for integer overflow on add/subtract and fall back to long math.

---

src/abstract.js
src/builtin.js
src/compile.js
src/complex.js
src/constants.js
src/dict.js
src/float.js
src/function.js
src/import.js
src/int.js
src/iterator.js
src/lib/array.js
src/lib/collections.js
src/misceval.js
src/object.js
src/str.js
src/structseq.js
src/type.js
src/typeobject.js

In this pull request, all of the get/set attribute functions are converted to take Python strings for the attribute names.  To make it more clear when a variable holds a Python string or a JS string, all variables holding attribute names are called ```pyName``` or ```jsName``` as appropriate.  Python strings for attributes are created once in ```constants.js``` so that they can be used directly.
There are two reasons for this change:
1. The attribute infrastructure can sometimes be relatively deep, and functions were converting names back and forth between Javascript and Python.  This pull request normalizes things so that you always pass down a Python string everywhere.  Previously, the internal functions took Javascript strings and the Python-facing functions took Python strings.  But, …

Normalize get/set attribute infrastructure to take Python attribute names

---

repl/repl.js

Little fix for the repl.
- `readsync` striped whitespace
- `console.log` tries to pretty print the error so a `.toString()` was required to make it nice.

readline-sync strips whitespace which is not ideal for python :D

---

src/str.js

This fixes #876.  This is a textbook example of why we shouldn't be messing with ```.v```.  Line 1145 mutated the internal representation of another string.  If that string were unique, it would be okay.  But, given that it's interned, this messes up all strings with the same original value now and in the future.
I don't think this affects #871, does it?
Please merge this quickly.

Fix string formatting bug that mutates interned strings.

---

dist-update.sh

As requested by @albertjan in #897, I believe this puts an ES5 build into skulpt-dist.  I am not sure how to test this, though, so please look over it carefully to decide if I'm doing the right thing.
It also seems like there is extraneous stuff in here now that the website has been migrated to use GitHub pages, but I left that alone.
We might also consider updating the README in skulpt-dist to explain what the builds are and how to use a CDN to use them directly from that GitHub repository.

Add ES5 and unminified builds to skulpt-dist.

---

src/str.js
test/unit/test_format.py

When formatting a string with the % operator, the '%' character
is encoded '%%' (eg '%d%%' % 100 -> '100%').
Skulpt's implementation was consuming an element from the value tuple
for '%%' literals, which was incorrect. This change fixes that, and
adds a test.

Stop %% escapes in %-formatted string from consuming a value

---

src/import.js
test/unit/subpackage/implicit_import.py
test/unit/subpackage/importable_module.py

`import *` wasn't obeying `__all__`. Now it does.
(NB - it does _not_ currently support importing submodules via `__all__`, but this is a strict improvement)

Obey __all__ in wildcard imports

---

src/parser.js
src/tokenize.js

The new tokenizer currently emits weird raw `Error`s without consistent line information. Make these `SyntaxError`s instead, with filenames and line numbers.

Make tokenization errors come out as SyntaxErrors with correct line numbers

---

src/import.js
test/unit/subpackage/implicit_import_2.py
test/unit/subpackage/importable_module.py

Well, this is embarrassing. I introduced a bug in #972 that broke the default `import *` policy (ignoring names that begin with `_`). This PR fixes (and adds a test for) that functionality.

Fix bug in default wildcard import policy. Add more tests.

---

src/compile.js
src/symtable.js
test/unit3/test_decorators.py

Previously, we only supported up to 1 decorator per function, and did not support class decorators at all. This PR fixes this.
---
In the process of writing the tests for this PR (which are quite closure-heavy), I discovered a nasty `symtable` issue -- namely, that `ste.hasFree` is not set for functions that _contain_ functions with free variables. For example:
```python
def f():
v = 4
def g():
def h():
return v+1
```
`symtable.js` did not set the `hasFree` flag on `g()`, even though it correctly notices that it has a free variable (`v`), because it computed the `hasFree` flag *before* walking child scopes (in this case, `h()`).
This actually appears to be a logic bug inherited from Python 2's `symtable.c`, which doesn't matter there because CPython's compiler doesn't rely on the …

Support multiple decorators + class decorators (+ symtable fix)

---

src/str.js
test/unit/test_regressions.py
test/unit3/test_compare.py

PR #986 broke string equality in Python 2 (doh). This PR adds tests to replicate and then fixes.
I'd like to fast-track this in; it's a small, tested fix to something previously accepted.

Un-break string equality in Python 2

---

repl/repl.js
src/abstract.js
src/ast.js
src/bool.js
src/builtin/sys.js
src/builtindict.js
src/compile.js
src/float.js
src/formatting.js
src/int.js
src/lib/datetime.py
src/long.js
src/module.js
src/str.js
src/symtable.js
test/unit/test_regressions.py
test/unit/test_strformat.py
test/unit3/test_compare.py
test/unit3/test_fstring.py
test/unit3/test_strformat.py

This is a follow-up to #975, which refactors the string formatting code so that it can be used by f-strings (and the built-in `format()` function too).
In other words, formatting like `f"{4+5:.2f}"` now works :-D
I took the opportunity to do a bunch of cleanup and bugfixing in our `str.format()` implementation, and re-enable/add a couple more tests to `test_strformat.py`, as well as enabling all the format-string-related tests in `test_fstring.py`.
(All the changes for this PR are in the most recent commit - everything else GitHub is showing us is part of #975.)

Refactor string formatting

---

src/abstract.js
src/compile.js
src/dict.js
src/function.js
src/misceval.js
src/type.js

This PR combines a series of performance improvements, totalling a ~45%~ **85%** speedup (aka a ~31%~ 46% reduction in runtime) on @rixner's student project ([`field.py`](https://gist.githubusercontent.com/rixner/f79dfa52a0385e5c82d147ae3d06c50c/raw/971a46b80c9ff79734e80f7bab49f66ecdc3ae11/field.py)).
Tagging @rixner because this is relevant to your interests, @albertjan because @rixner is busy, and @LeszekSwirski for arcane mysteries of V8 performance.
I'd suggest reviewing each commit individually: Each improvement is a single commit, with a paragraph of notes in the commit message.
Performance numbers throughout use the median of 10ish measurements on my laptop, of 500 ticks of `field.py`. (I made a desultory effort to get the CPU throttling into a consistent state, but it's pretty …

Performance improvements

---

src/formatting.js
test/unit3/test_strformat.py

Small change to the `formatting.js`
Currently
```
>>>"{:.2%}".format(-0.05)
--0.05%
```
This pull request fixes this bug.

fix formatting with negative percentages

---

src/builtin.js
src/list.js
src/main.js
src/misceval.js
src/range.js
src/tuple.js
test/unit3/test_range.py

This is an implementation of Python3's range object.  It allowed me to uncomment many of the commented out tests in test_range.py.
It computes the entire range ahead of time instead of being a generator object, which is no worse than what we do now.  But, that means it is inefficient for large ranges.  But, a lot of other capabilities are improved.

Implement Python3 range object

---

package.json
src/lib/math.js

#1004 uses ```BigInt``` which wasn't introduced into node until version 10.4.  Update engines in package.json.  Also update some other packages that npm complains have security issues.

Update node packages and engines.

---

src/builtindict.js
src/import.js
test/unit3/test_inheritance.py

This fixes #1046. 
I believe the algorithm for `setUpClass` was not quite right for builtins as it checked `child.tp$base` but the actual base class is located at `child.prototype.tp$base`
This effectively meant that all builtins had an attribute `__bases__ = ()` 
I added some failing tests. 
My first attempt failed because I unknowingly included `sk$abstract` classes in `bases`. The final commit corrected this, adding a check to ensure that a potential parent did not have `sk$abstract = true` before pushing it to bases. 
___
While I'm here I add a `.__name__` atribute to all builtins. 
And fix the `.__mro__` property
___
**Example fixes:**
```python
>>> issubclass(int, object)
True  # previously False
>>> int.__bases__
(<class 'object'>, ) # previously empty tuple
>>> int.__mro__
(<class …
```

Builtin Inheritance

---

src/lib/unittest/__init__.py
test/unit3/test_math.py

It is common to have to comment out `with self.assertRaises` or any `self.assertRaises` that has `kwargs` from Python unit tests 😢 . 
This pull request aims to close #1027, it:
- adds context manager support to `assertRaises`. 
- allows `kwargs` for `assertRaises`
- fixes the `repr` when an `assertRaises` test fails - currently you just get `Fail:` since `str(TypeError())` is empty
- uses code from cpython as a template and adapts to the Skulpt unittest module.
I uncommented a few of the `test_math.py` that included `with self.assertRaises` - I wasn't sure what other tests to add...?

assertRaises as a context manager and kwarg support

---

src/import.js
test/unit3/test_inheritance.py

A small amendment to fix #1051 
A base must be in the `Sk.builtins` dict in order to be a parent class...

fix inheritance for py3 StandardError

---

src/builtin.js
src/import.js
src/type.js
test/unit/test_builtin.py
test/unit3/test_builtin.py

This pr aims to fix #1078 
The approach I took was to add the appropriate `tp$setattr` function to builtin type and type objects 
This negates the need to check whether an object is a builtin in the `builtin.setattr` function

setting attributes of builtin types should fail

---

src/lib/turtle.js

A one-line fix to close #1081 
Adding the `co_name` to the wrapped function provides correct error messages.

add co_name to wrappedFn

---

repl/repl.js
support/build/help.js

Adds `py2` or `py3` as required parameter to `npm run repl`
```
➜  skulpt git:(master) ✗ npm run repl    
> skulpt@1.0.0 repl /Users/albertjan/skulpt
> node repl/repl.js
Using skulpt.min.js
error: must specify python version (py2/py3) and python program to run
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skulpt@1.0.0 repl: `node repl/repl.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skulpt@1.0.0 repl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/albertjan/.npm/_logs/2020-05-25T12_45_56_434Z-debug.log
➜  skulpt git:(master) ✗ npm run repl py2
> skulpt@1.0.0 repl /Users/albertjan/skulpt
> node repl/repl.js "py2"
Using skulpt.min.js
Python …
```

add py3/py2 switch to commandline repl

---

src/builtin/this.py

Fixes `SyntaxError: bad input on line 28` when running with `__future__: Sk.python3` and still works for Python 2.

Upgrade this.py to Python 3

---

src/file.js

A one line change to `file.write` which should return `None`. 
This is problematic if the user ever does
```
print(print('foo'))
x = print('foo')
type(x) # x is not defined
```

fix small bug for print

---

repl/repl.js
src/import.js

this pr aims to improve the hack with `classmethod` with an additional hack 🤷‍♂️ 
It essentially removes the `__module__` property from each of `property`, `classmethod` and `staticmethod`
It also removes these three objects from `Sk.globals` since they get added to `__builtins__` and shouldn't really be in `Sk.globals`
this way
```python
>>> classmethod
<class 'classmethod'>
>>> globals()
{'__name__': '__main__', '__file__': 'repl.py', '__doc__': None, '__package__': None}
```
a small change to `repl.js` which - since it retains globals carries over the `__name__` property `__builtins__.classmethod` 
By setting the `Sk.globals.__name__` property in advanced this remains the same after `classmethod` et al are injected

improve __bulitins__.classmethod.classmethod

---

src/long.js
test/unit/test_int.py
test/unit3/test_math.py

A fix to close #1113 
the issue seems to be in the `biginteger` library
https://github.com/skulpt/skulpt/blob/master/src/biginteger.js#L878
```javascript
return ((this[1] & ((1 << (32 - this.DB)) - 1)) << this.DB) | this[0];
```
the bitwise operations can return unexpected results for largish integers (`>2**31`) and the threshold we use internally for this function is `Number.MAX_SAFE_INTEGER`... (`2**53 - 1`)
```javascript
a = new Sk.builtin.biginteger(2**31)
a.intValue() // -2147483648 
a.toString() // "2147483648"
b = new Sk.builtin.biginteger(2**32 + 1)
b.intValue() // 1
b.toString() // "4294967297"
```
`biginteger.toString()` seems safer for this use case then... 
I replace `this.biginteger.intValue()` with `parseInt(this.biginteger.toString(), 10)` 
We know this is safe internally …

fix for long.toInt$

---

src/import.js
support/run/run_template.ejs

A minor bug that I found when working on #1110 
If the supplied body is a string it should still be compiled - even if that string is empty. 
Otherwise the compile logic tries to find `.py` in `builtinFiles`
I didn't add tests but I did make the default code in `npm run brun` an empty string rather than a new line. 
A quick check of this branch vs master `npm run brun tok_test.py` will compile an empty line whereas before it would raise the error
```
ImportError: No module named <stdin>
```

compile pyBody if supplied string even if empty

---

src/str.js

This one improves performance for strings but only if doing a lot of str conversion like
```python
from time import time
for j in range(2):
t = time()
for i in range(3000000):
str(i)
print(time()-t)
```
the first loop sets strings into `interned` 
the second will get strings from `interned`
By using 
```javascript
Sk.builtin.interned = Object.create(null)
``` 
instead of 
```javascript
Sk.builtin.interned = {}
```
there's no need for `"1"+ ret` since there won't be any name conflicts with `Object.prototype` since `Sk.builtin.interned` no longer inherits from `Object` and thus has no `__proto__` methods that would otherwise cause conflict.

improve performance of interned

---

src/lib/operator.js
src/lib/tokenize.js
src/print.js

3 changes in places using `callsim(OrSuspend)Array` where this is our internally preferred callsignature
I also remove this in one place where it makes more sense to directly call the JS function.

use of callsimArray

---

src/lib/random.js
src/lib/string.js
src/range.js

this pr is a suggestion - since we've made the conclusion that `tp$getattr` should only use `pyStrings` I think we should do something similar for `mp$subscript` which can currently accept `numbers`
this pr does not make that a requirement but simply picks up the places where internally we are using number as the index for `mp$subscript` instead of `Sk.builtin.int_`
(I will comment at each place) 
I put `random.js` through prettier - hence the semi colons. 
I also provided a fast case for `random.shuffle` which typically will receive a `list`

only send ints to mp subscript not number

---

src/import.js
test/unit3/test_inheritance.py

this pr fixes a bug I brought in with #1049 
in skulpt
```
>>> bool.__bases__
(int, object)
```
in python
```
>>> bool.__bases__
(int,)
```
All builtins only have one base in their bases tuple 🤦

builtins have a single base in bases

---

src/compile.js
src/generator.js

a niche bug
```python
def f():
x = yield
yield x
>>> gen = f()
>>> next(gen) is None
Error can't read ob$type of null
```
We send null rather than `Sk.builtin.none.none$`

change null to none

---

src/lib/math.js
support/build/wrapmodules.js
test/unit3/test_math.py

4 types of changes to math.js
use of `new` keyword
make sure all js funcs have names to avoid the dreaded `<native JS>`
put it through prettier
a couple of var/cons/let adjustments
No change to logic in this pr. 
_edit: 
I've added a change to Babel minifier for stdlib to preserve func names so that things like `print(math.ceil)` work as expected for the user._

Pr/math `new`, <native JS>, some formatting

---

src/dict.js
src/env.js

I don't know why this seems to improve performance on my machine... 
It seems trivial and I was hoping someone could confirm/explain what's going on here!
it accounts for my claim that #1013 improved speed significantly. It's not that #1013 significantly improved speed but more that the #1013 branch was prior to the inclusion of `Sk.setupDictIterators` which seemed to slow down speed by approx 50% somehow...
It doesn't matter if I do `npm run build` or `npm run devbuild`
I was using `fields.py` `100 Ticks` `10 loops`
I got `3.4 seconds` vs `1.9 seconds` which seems ridiculous.
I hope there's a sensible explanation 🙏

This shouldn't improve performance

---

src/abstract.js
src/bool.js

in `objectPositive/Negative` we handle `bools` as if they are a special case but since they are instances of `int` they are not special and so can be treated as per all other number types with an `nb$positive/negative` slot.

handling of bool in abstr.objectPositive/Negative

---

src/builtin.js
src/complex.js

simplify the logic in `builtin.abs` since `float_`, `int_` have `nb$abs` slots. All `klass` objects also gain an `nb$abs` added if `__abs__` is set.
I adjust complex.js to include an `nb$abs` slot where it didn't previously exist.

adjust builtin.abs to directly call nb$abs

---

src/compile.js
test/unit3/test_decorators.py

fix #1147 
This seemed a sensible fix but perhaps there's a better way.

decorators run in reverse order

---

src/bool.js
src/misceval.js

this pr adjusts richCompareBool and fixes an issue where 
```python
>>> None < None
False # yes in py2 No in py3
``` 
in py3 mode this should be an Error. 
It simplifies some of the logic in the function. 
It is also fixes a couple of issues with number types and the `is` operator. 
e.g. 
```python
>>> True is 1 #should be false
True # in skulpt we treat is the same for instances of number but shouldn't
>>> class A(int): pass
>>> A(1) is 1
True # should be False - same issue with bool - A(1) is an instance of int...
```
Because the above was a hidden bug in skulpt it meant that we were not getting correct results from
```python
self.assertTrue(True & True) 
```
So I override `Bool` number slots [as per Cpython](https://github.com/python/cpython/blob/master/Objects/boolobject.c#L95). 
For …

adjust richCompareBool

---

src/compile.js
src/complex.js

Currently we use `Sk.builtin.float_` to represent complex number real and imag parts
this pr changes the internal representation to javascript numbers. 
It simplifies `complex.js` somewhat as we no longer do `this.real.v` but just `this.real`

complex internal representation

---

src/constants.js
src/object.js
src/type.js
test/run/t421.py.real
test/run/t421.py.real.force

this pr adjusts `object.prototype.$r`
It basically takes the `else` part of `klass.prototype.$r` and moves it to `object.prototype.$r`
which i think is more correct.
it adjusts a previous test
```python
>>> object()
<object object> # previously <object> in python this is <object object at 0x123...>
```
while i'm here I adjust `klass.prototype.$r` and `tp$str` to use `callsimArray`
As well as adding a constant `Sk.builtin.str.$module`

change object.prototype.$r to be more inline with python

---

src/lib/itertools.js
src/list.js
src/misceval.js
src/tuple.js
src/type.js
test/unit3/test_suspensions.py

This Pr adds a helper function `Sk.misceval.arrayFromIterable`
it is suspension aware and uses the `sk$asarray` architecture from #1054  where possible.
The function will raise a `TypeError` if the object is not iterable.
As well as a suspension error if the iterator suspends but `canSuspend` is `undefined || false`
I adjust the constructors of `tuple` and `list` to use this function. 
This adjustment allows `tuple` to be suspension aware. (tests added in `test_suspensions.py`
I also identify a few places in `itertools` where this function is beneficial. 
`sk$asarray` is designed for builtins so I add the flag `hp$type` to all instance of `klass` objects and check this flag before using the `sk$asarray` architecture within `arrayFromIterable`.

arrayFromIterable - (tuple suspension aware)

---

src/abstract.js
src/builtin.js
src/env.js
src/function.js
src/import.js
src/method.js
src/object.js
src/type.js
src/typeobject.js

this pr is for the correctness and aims to fix #1079
It moves in the direction of `tp$_____` existing on the prototype of all type objects and not mixing and matching.
---
While working on this pr there were errors in the messages for methods because the logic was getting the `typeName` of the `im_class` which is now `type` 
This pr aims to improves the logic in `Sk.builtin.method`. It sets the `tp$name` of a method instance to the `im_class` it is bound to.
There is still work to do with methods since unbound methods are depreciated in python 3. 
But this pr only aims to fix using the correct type names.
---
Suggestions and suggested tests?
example of when the current set up fails, is when you try to do something with a klass that you shouldn't be able to... e.g. 
```python
class A: pass …
```

move tp$name onto the prototype of the klass

---

src/builtindict.js
src/errors.js

This pr takes the opinion that we are preferring `python 3` and making sure `python 2` doesn't break.
To keep StandardError in the game I make `StandardError` = `Exception` in the switch. 
I can't imagine this would break any code since using `StandardError` in code would be unusual, which I guess is why it's not in `python 3`...
But maybe there is a weird case where this will break some code somewhere that I haven't considered.

remove StandardError from error.js

---

src/errors.js

I introduced a regression - not realising there are two occasions when the internally called `SyntaxError` has 4 arguments. 
This very minor adjustment fixes that regression. 
I think this should be a quick merge.
```python
print 'foo'
```

fix error message regression

---

src/abstract.js

a small update to the error message in `Sk.abstr.gattr` which I meant to do in a previous pr (I think it got lost in the rebasing). 
```
>>> class A: pass
>>> A.default
type object 'A' has no attribute 'default'
```

improve error message and no need to unfixreserved

---

src/ast.js
src/builtin.js
src/builtindict.js
src/bytes.js
src/compile.js
src/constants.js
src/errors.js
src/function.js
src/misceval.js
src/str.js
src/symtable.js
test/unit/test_unicode.py
test/unit3/test_bytes.py
test/unit3/test_fstring.py
test/unit3/test_string_methods.py
test/unit3/test_suspensions.py

This pr is the aim to marry the unicode work in #983 and the bytes work in #989 
The diff to #989 can be seen here s-cork#7 (diff fixed to be more readable with latest changes rebased)
The approx diff with #983 can be seen at s-cork#10
_(it's not totally accurate since it was after a merge commit of #983 on top of #989 but it's approx accurate. 
You can see - the minor change to ast.js, 
change in `compile.js`
removal of `builtin.staticfunc` and `misceval.iterator` (additions in #983 branch)
adjustment to `builtin.ord` 
cleanse of bytes from `str.js`)_
**AST** 
changes here are from #983 
I made no change of the #983 algorithm apart from making sure the ascii characters were `< 0x7f` rather than `0xff`
This means that `b'¥'` is now correctly thrown as a `SyntaxError` which was not the …

combine #989 #983

---

src/import.js

a couple of places where import statements could avoid a try catch by using `dict.mp$lookup` over `dict.mp$subscript`
the former returns `undefined` whereas the latter throws an error.

import use mp_lookup and avoid try catch

---

src/lib/unittest/__init__.py

working on implementing these tests from `dict_tests.py` led to a couple of small bugs relating to `assertRaises`
https://github.com/python/cpython/blob/c3dd7e45cc5d36bbe2295c2840faabb5c75d83e4/Lib/test/test_dict.py#L767
https://github.com/python/cpython/blob/c3dd7e45cc5d36bbe2295c2840faabb5c75d83e4/Lib/test/test_dict.py#L201

fix assertRaises related bug

---

src/compile.js
test/unit3/test_errors.py

```python
>> raise 1
TypeError: exceptions must derive from BaseException
```
This fixes a small issue that the user should only be able to raise `Exceptions` if they are instances of `BaseException` or classes that derive from `BaseException`

raise error with non Exception should raise an error

---

HACKING.md
example/ipython.css
example/ipython.html
example/ipython.js
example/turtle.html
example/webgl/webgl-0001-basic.html
example/webgl/webgl-0002-viewport.html
example/webgl/webgl-0003-color.html
example/webgl/webgl-0004-movement.html
example/webgl/webgl-0005-3d.html
repl/repl.js
src/env.js
support/run/run_template.ejs
test/turtle/referenceImageCreator.html
test/turtle/spec/TurtleSpec.js

I wanted to create a new example - potentially could be added to the website instead - but I thought i'd showcase it as a PR. 
it uses `ace` code editor. I'm sure I could adapt it to `codemirror` if preferred. 
here's the gif:
___
The ipyhton repl adds keyboard bindings to scroll through previous entries
as well as a keyboard interrupt feature `ctrl + c`
`ctrl/cmd - enter` runs the command
`_`, `__`, `_1` work as per ipython
as do `In`, `Out`, `_i1`, `_ii` 
___
A couple of suggested changes with this pr - 
`Sk.retainGlobals` should match camelCase for `options["retainGlobals"]` (with backward compatibility)
Every example has the same `builtinRead` function should this become the default option?
Since it's the default option I remove this function from all examples. 
Both the above changes …

ipython example

---

src/lib/array.js
src/lib/document.js
src/lib/image.js
src/lib/processing.js
src/lib/re.js
src/lib/turtle.js
src/lib/webgl/__init__.js
src/misceval.js

this pr makes a minor adjustment to `Sk.misceval.buildClass`
there are some cases in `lib` `js` files when the global object passed to `Sk.misceval.buildClass` does not have a `__name__` property. 
This is true of the `re.js` module for example. 
This might become problematic because when `locals.__module__` is set to `undefined` it will later create a dictionary where the `__module__` value is also `undefined`.
This hasn't caused issues in the codebase but I think it would be good to eliminate setting a value of a dictionary to be undefined. 
In cpython doing the equivalent of `mp$ass_subscript(key, undefined)` would be the equivalent of deleting that item from the dictionary. 
the `klass` `__module__` will be set to `Sk.globals.__name__` later anyway if it was not set in `locals`.

don't set __module__ unless globals.__name__ exists

---

src/dict.js
src/errors.js
test/unit3/test_sets2.py

`LookupError` was recently introduced with `bytes`
this pr tidies a couple of related loose ends
```python
>>> KeyError.__bases__ 
(LookupError,) 
```
When a `KeyError` is thrown from a dict lookup we should throw the `KeyError` with the actual `key` and not the `repr`
```python
d = {}
x = 1
try: 
d[x]
except KeyError as e:
print(e.args[0] is x) # currently in skulpt the dict key lookups return the `repr` and so this would fail
```

LookupError

---

src/frozenset.js
src/set.js
test/unit3/test_frozenset.py

**Builtin on top of #1091**
I built this ontop of #1091 since it relies on `Sk.builtin.dict` having an `sk$asarray` method which that pr adds. 
I also add the `sk$asarray` method to `frozenset` and `set`
One of the benefits of a `frozenset` is that it is `hashable`. But in order to be `keys` of a `dict` the `hash` function must be consistent. 
This pr takes the general approach of python 2.7 https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Objects/setobject.c#L775
Mostly because it was easier to follow 🤷‍♂️ 
I add the relevant tests from `python3` that test the `frozenset` `hash` function being consistent...
For the diff see https://github.com/s-cork/skulpt/pull/6

frozenset hash

---

src/bytes.js
src/str.js
test/unit3/test_bytes.py

extension of the bytes pr
this pr adds support for bytes `nb$remainder`
Rather than rewrite `nb$remainder` it piggybacks off `str.prototype.nb$remainder`
To fully support `nb$remainder` bytes objects must have the ability to be keys of dictionaries. 
The current `hash` function is not suitable since two `bytes objects` that are the same in python have different in `hash` values in skulpt.
```python
>>> hash(b'x') == hash(b'x')
False # should be True
```
Skulpt/Python `hash` function for `str` is consistent because of `interned`
in Python, the `hash` function for `bytes` is the same as for its `str` counterpart
```python
>>> hash('x')
-3753845217207833703
>>> hash(b'x')
-3753845217207833703
```
so for the `bytes` `hash` function it make sense to take the same value that is returned by the …

bytes mod hash

---

src/list.js
src/slice.js
src/tuple.js

this pr aims to simplify `sssiter$` and make the function more readable.
it now takes two arguments
- `len - number`  (instead of a `length` or an `object` whose `v` property has a `length`) 
- `function` which expects javascript `index` at each iteration.
(rather than using an argument `wrt` at each iteration (previously defined as the outcome of `Sk.builtin.asnum$(wrt)`), it instead relies on closure in the same way that `Sk.misceval.chain` would use closure.)
I don't think this is breaking since it's fairly obscure function buried in the core. Used for `str`, `tuple` and `list`
In the functions that use `sssiter$` I also adjust `const/let/var`

adjust call signature and implementation of sssiter

---

src/float.js
src/long.js
test/unit3/test_float.py

this pr adjusts the constructor of `Sk.builtin.float_`
There are two motivations
1. in #828, I incorrectly asserted that an overflow error should be raised for large strings. But actually this is not the case 
```python
float(str(2**1024)) # inf
float(str(2**1024)) # Overflow Error
```
Overflow Error should only be raised for large ints (in skulpt's case large longs)
2. returning inside a constructor stops a builtin from being subclassable. We were testing some instance of subclassing float but not all. e.g.
```python
>>> class MySimpleFloat(float): pass
>>> MySimpleFloat()
nan # failed because the constructor was doing... return new Sk.builtin.float_(0.0); rather than this.v = 0.0;
>>> MySimpleFloat('5')
nan # failed for a similar reason
```
---
- to fix 1 I move the `Overflow` error to …

adjust constructor for float and move overflowerror

---

README.md
src/lib/antigravity.js
src/lib/antigravity.py
src/lib/webbrowser.js

Hi! This is my first PR for this cool project, looking forward for more chances!
- Like `antigravity.js` does, using `window.open(url, "_blank")` for `webbrowser.open(url)`.
- A `TypeError` will be raised if `url` is not `str`.
Please let me know if I'm making things correct, thanks in advance!

Implement the 'webbrowser' module

---

src/abstract.js
src/ast.js
src/compile.js
test/unit3/test_suspensions.py
test/unit3/test_unpack.py

This pr aims to add support for starred assignment - close #1063 
```python
>>> a, *b, c = 1, 2, 3, 4, 5
>>> a
1
>>> b
[2, 3, 4]
>>> c
5
```
general approaches were taken from Cpython's ast and compile files
It even works on weird nested assignment! who knew that was a thing...
```python
>>> a, *[b, *[c, *d]], e = range(6)
>>> a, b, c, d, e
(0, 1, 2, [3, 4] 5)
```
---
**TODO**

starred assignment unpacking

---

src/classmethod.py
test/unit3/test_builtin.py

Our implementation of `@classmethod` doesn't support keyword arguments. Fix it.

Support keyword arguments in @classmethod

---

src/compile.js

This fixes a potential problem where the `this` might be undefined if a function wakes from a suspension.
Mostly `this` is `window` when a function wakes form a suspension but I have found this bug in the wild when it becomes `undefined` or `null`
I can't seem to reproduce it with a test in skulpt.

fix a problem with compiled code after waking from suspension

---

src/builtindict.js

If Python3 mode is preferred in Skulpt, then the raw_input function shouldn't be available.
Credits: [comment](https://github.com/skulpt/skulpt/pull/1221#issuecomment-716921934) from @s-cork

feat(builtin functions): remove raw_input function in python3

---

src/lib/processing.js

The parameters were named x, y, and x, but it looks like they wanted to be x, y, and z.
This probably causes very unexpected behavior for anyone trying to set 3D coordinates in processing.js
First-time contributor, so I'm still getting up-to-speed on reading the docs on contributing, so please feel free to let me know if there's anything else you'd like me to do before submitting this.

Fix xyz typo in processing.js

---

src/lib/math.js
test/unit3/test_math.py

With the previous version, the code:
* `print(math.sqrt(-1))` and 
* `print(math.sqrt(float("-inf")))` 
will both print out "nan", while it should raise a `ValueError: math domain error`. 
ref: https://github.com/python/cpython/blob/dd2804790dfa116d20e37bc6b4463c07586da76c/Lib/test/test_math.py#L1154

fix(math.sqrt): sqrt should raise ValueError when passed a negative number

---

src/lib/time.js
test/unit3/test_time.py

Follow-up to the aside in #1231 regarding the failed `TimeTestCase.test_strftime` test.
If I'm reading it right, Skulpt's implementation of `time.timezone` uses the offset as of 2002.  I'm in Ireland and [the history of its civil timekeeping](https://en.wikipedia.org/wiki/Time_in_the_Republic_of_Ireland#History) means that its timezone offset was different in 1970 compared to 2002.  It's likely that developers in other timezones weren't seeing this failure.  This PR updates the test to use a moment in 2002, for consistency with how `timezone` is computed.  I've checked it under timezones `Europe/Dublin`, `America/Denver`, `Europe/Istanbul`.
This PR also extracts a function from near-duplicated code between Skulpt's `localtime()` and `gmtime()` implementations, and fixes a minor typo.

Refactor time module and fix its tests

---

src/lib/processing.js

* `exitp()` function shouldn't take any parameters
* in the vector class's div function, fix the function name typo `dic`, it should be `div`

Fix(processing.js): exitp and PVector's div function

---

src/formatting.js
test/unit/test_strformat.py
test/unit3/test_strformat.py

The code is taken from pull request: https://github.com/skulpt/skulpt/pull/1016
The author of that 1016 pull request seems hasn't responded on that thread for several months, and it could be an easy merge, so I am just remaking the pull request based on the discussion in that thread.
**All credits** should go to @darkaardvark2  and @meredydd 
(If this pull request violated some credits rule, please feel free to close/delete it)

fix scientific notation string formatting (remade)

---

src/lib/time.js
test/unit3/test_time.py

As @s-cork notes in #1233, I overlooked a usage of `localtime_f()` in that refactoring, sorry.  Add a test for the situation where this comes up, and fix the failure by using the new `from_seconds()` instead.

Bugfix: Overlooked localtime f usage

---

src/compile.js
src/function.js
test/unit3/copydocstring.py
test/unit3/overwritedocstring.py
test/unit3/test_docstring.py

Give `__doc__` attribute or property to functions, methods, classmethods, classes, and modules.
Simpler replacement for #1261, based on machinery added by #1092.
I'm not fully sure about 5f983e3.  It assumes that the passed-in `code.$doc`, if present, is already a Python object.  Should the code assert that `code.$doc`, if not `undefined`, is either a Python string or `None`?  Should it allow a JavaScript string, and convert to a Python string on construction of the `builtin.func`?  Those might be questions for a separate PR, and are related to #1263.

Partial docstring support (post #1092)

---

test/unit3/test_del_attr.py
test/unit3/test_raising_descriptor_get.py

Add some (passing) tests for:
* deleting attributes, taken from #1248 (which was closed as superseded by #1092)
* a corner case for `hasattr()` which failed pre-#1092

Add some attribute and descriptor tests

---

.github/workflows/test.yml
.gitignore
README.md
package-lock.json

This adds a workflow to run our unit tests and would allow us to remove Travis-CI.
Thanks to @timmartin for the test.yml file.
The only real change to the repo is that we will add the package-lock.json file, which is recommended practice anyway, to the repo.

Simple workflow to run unit tests

---

src/builtin.js

Small change - a couple of typos in the error messages for the max function

fix a typo for max errors

---

src/compile.js

Currently, if the yieldLimit is set and you yield from a deeply nested long running function, state may be lost.
The situation occurs when you resumqe from a yield. At that point, each Python function resumes it's children.  However, if one of those children exceeds the yield limit again before returning, it will return an Sk.yield suspension.  That gets stored in ```$ret``` in ```$wakeFromSuspension```.  The code then enters the main while loop, where it detects that it is past the yield limit.  At that point, it creates a *new* yield suspension (throwing away the suspension currently stored in ```$ret```) and returns that.  This will occur all the way back up the chain.  When you try to resume again, all state is lost.
This pull request simply guarantees that you will run through the …

Fix resume from yielding

---

src/abstract.js
src/builtindict.js
src/function.js
src/generic.js
src/lib/functools.js
src/lib/functools.py
src/type.js
test/unit3/test_functools.py
test/unit3/test_itertools.py

this is a branch off of #1092 - separate branch so as not to continue to pollute that pr. 
It will fail on Travis at present since it heavily relies upon #1092 but passes all tests on my local machine.
it introduce a partial implementation of functools. 
- `partial`
- `partialmethod`
- `update_wrapper`
- `wraps`
- `cmp_to_key`
- `total_ordering`
- `reduce` (suspension aware)
All the above are written as native skulpt functions/classes 
This is different to Cpython, which mixes between C implementations and python implementations.
All the above use the full set of cpython tests (minus `pickling` and other unsupported tests).
some additions were made to the core and the diff with #1092 can be found here https://github.com/s-cork/skulpt/pull/13
most of those changes are relatively minor.

functools implementation with tests

---

using.md

The release notes on the "Using Skulpt" page are currently showing up as raw Markdown text, this change causes them to be transformed to HTML.

Expand Markdown formatting in release notes

---

src/ast.js
src/lib/functools.js
test/unit3/test_functools.py

This extends the functools implementation to include `lru_cache`.
It also adds the `@cache` decorator which was included in python 3.9
I used the cpython tests and adjusted for skulpt.
As part of the pr I also assigned Sk objects into the local scope for functools.

functools: implement lru_cache

---

repl/repl.js
src/builtin.js
src/builtindict.js
src/compile.js
src/import.js
test/unit3/test_builtin.py

This is a cherry picked commit on top of #1092
A suggestion for exec. 
I have suggested two implementations:
internal implementations are called via `Sk.builtin.exec`
and python are called via `Sk.builtins.exec`
The reason for separate implementations is that...it could be quite nice to pass a javascript object for globals and locals.
```javascript
globals = {foo: new Sk.builtin.str('bar')}
Sk.builtin.exec("print(foo)", globals)
```
But i'm not wedded to an approach. 
I've been working on implementing dataclasses - as a first step to get the module to work using the version in python - exec was necessary. So here it is...
UPDATE:
- I've limited to globals, locals only being dictionaries when called from python, whereas, Cpython supports dicts for globals and any mapping for locals. This …

make exec work

---

src/builtin.js
src/compile.js
src/errors.js
src/generator.js
src/simple_iterators.js
src/slotdefs.js
src/symtable.js
test/unit3/test_yield_from.py

In the move to python3 `yield from` is a feature that we're obviously missing.
This pr implements that feature.
Since `StopIteration` sends values up the chain of subiterators and Skulpt looses the value when `tp$iternext` is called, I put the value property from the `StopIteration` on the iterator itself.
This pr is 1 commit ahead of #1092. You can see the diff in the last commit: a4cbf3c
I implement all the tests from Cpython
I make no attempt to implement `throw` or `close` methods for generators and leave these features as outside the scope of this pr.
Tests that required `throw` and `close` were commented out.

Implement yield from

---

src/abstract.js
src/compile.js
src/constants.js
src/dict.js
src/enumerate.js
src/errors.js
src/function.js
src/generic.js
src/generic_alias.js
src/lib/collections.js
src/lib/functools.js
src/lib/itertools.js
src/lib/types.py
src/list.js
src/main.js
src/mappingproxy.js
src/misceval.js
src/nonetype.js
src/object.js
src/set.js
src/symtable.js
src/tuple.js
src/type.js
test/unit3/test_generic_alias.py
test/unit3/test_types.py

this pr adds support for `__class_getitem__` (closes #1146 )
it implements partial support for pep 585: https://www.python.org/dev/peps/pep-0585/
```python3
list[int, ...]
dict[str, int]
type[int]
from itertools import chain
chain[list]
```
it provides code for `__mro_entries__` but since this is not checked in skulpt `class A(list[int]): pass` does not work
similarly `__instancecheck__` and `__subclasscheck__` are not yet called.
some of the cpython code accounts for `typing.TypeVar` but since that is not yet a thing much of the implementation doesn't yet make sense in skulpt. 
This won't work on master and builds on top #1092
All the tests in this pr are working on another branch. 
Tests taken from Cpython.

support generic alias

---

src/generic_alias.js
src/tuple.js

This piece of api snuck in with #1216 and shouldn't be there.
I think it was just a hangover from some initial experiments.

Remove forEach api that snuck in

---

src/builtin.js
src/compile.js

I have no idea why this makes any difference to the repl.js speed. 
It only affects the repl and doesn't affect running in the browser.
It also only affects devbuild and not build.
The cause of slowness was from commit 6100446677f755384c64e4ec3bae30ed068688b4 which added `var` before `$compiledmod`. 
Removing the `var` also fixed the slow speed of repl.js.
Adding `"use strict";` before `var $compiledmod` also fixed the speed.
(but we can't add `"use strict";` because of the way skulpt handles local variables in compiled python functions)
I only found this fix because `Sk.importMainWithBody` was fast in `repl.js` and experimenting with a few differences between `Sk.builtin.exec` and `Sk.importMainWithBody` I stumbled across using `Sk.global["eval"]` instead of `eval`. Which doesn't make …

fix slow repl.js

---

src/abstract.js
src/builtin.js
src/object.js

brings error messages up to date with cpython error messages for `format` and `__format__`

Improve error messages for __format__

---

src/lib/datetime.js
test/unit/test_datetime.py

Because in python2 rounding a float returns a float - it becomes a problem when we assert that certain values are python integers if we happen to be in python2 mode.
`timedelta(minutes=0)` will fail in python2 mode...

Adjust the round function in datetime.js

---

src/compile.js
test/unit3/test_skulpt_bugs.py

The bug happens becuase `__str__` gets called before the instance is instantiated. Because calling `toString` on a skulpt object calls it's repr.
(it's a 1 line change the rest are tests)
close #1345

fix bug #1345

---

src/ast.js
src/tokenize.js
test/run/t246.py.real

When the skulpt tokenizer produces a `NUMBER` token we know it's positive and:
- a valid int literal
- or float
- or purely imaginary complex number
We don't need to do quite as much work to turn it into the correct python type.

reduce parsenumber complexity

---

src/formatting.js
test/unit3/test_float.py

The following code:
```python
print(f'{-0.003:6.3f}')
print(f'{0.003:6.3f}')
print(f'{-1.234:6.3f}')
print(f'{1.234:6.3f}')
```
Produces the following output:
```python
0.003
0.003
1.234
1.234
```
Instead of.
```python
-0.003
0.003
-1.234
1.234
```
Test taken from cpython.
I took the whole test class and commented out the tests that are beyond the scope of this pr.
This bug is covered by `FormatTestCase.test_issue35560`.

fix float formatting when the width is is specified for negative values

---

src/compile.js
test/unit3/test_suspensions.py

the compile code assumed `Sk.builtin.bool` could suspend but i don't think that's ever been the case.
This pr fixes this by only calling `Sk.builtin.bool` after the call to `__contains__` has completed any suspensions.

fix __contains__ can't suspend

---

src/lib/time.js

it's possible to get negative timestamp differences in skulpt
But all timestamps should really be monotonically increasing 
(unless the system time was changed between calls)
```python
from time import time
t = time()
for _ in range(1000):
if time() < t:
print('back in time!')
t = time()
```
This pr fixes that with an implementation that entirely depends on the browser `performance` api.
(falling back to the `Date.now()` api if the `performance` api is not available)
The previous implementation combined the two apis which led to negative timings since the fractional offset was not accurate with respect to `Date.now()`.
I've added comments for browser compatibility links to mdn.
I haven't added additional tests since node doesn't support `performance` without a `require('perf_hooks')`.
--- …

time.time() should be increasing

---

src/errors.js
test/unit3/test_suspensions.py

Oops - when injecting python Exceptions in #1343 SuspensionError got lost.
Added a test.

Fix: accidental removal of SuspensionError

---

src/misceval.js

With SuspensionErrors, we throw the error at the location where we couldn't handle a Suspension.
This might be incredibly frustrating to debug
e.g. 
```python
from time import sleep
def foo():
sleep(.1)
class A:
def __iter__(self):
foo() # I block
return iter([1,2,3])
a = A()
for _ in a:
pass
```
If the user got an error at line 12 they'd have little idea how to deal with it.
But whenever a Suspension occurs in Python we have traceback information based on the child suspensions.
So we can fill our traceback with information that can then be reported to the user.
e.g.
```text
SuspensionError: Cannot call a function that blocks or suspends here
at Form1, line 4
called from Form1, line 8
called from Form1, line 12
```

Support a traceback for SuspensionErrors

---

test/unit3/test_math.py

After #1369 cpython updated their tests in https://github.com/python/cpython/pull/28595
This pr updates our own set of prod tests to match.

update math test_prod with recent cpython changes

---

src/compile.js
src/import.js
src/module.js
test/testunit.js
test/unit3/test_import/__init__.py
test/unit3/test_import/data/circular_imports/basic.py
test/unit3/test_import/data/circular_imports/basic2.py
test/unit3/test_import/data/circular_imports/binding.py
test/unit3/test_import/data/circular_imports/binding2.py
test/unit3/test_import/data/circular_imports/from_cycle1.py
test/unit3/test_import/data/circular_imports/from_cycle2.py
test/unit3/test_import/data/circular_imports/indirect.py
test/unit3/test_import/data/circular_imports/rebinding.py
test/unit3/test_import/data/circular_imports/rebinding2.py
test/unit3/test_import/data/circular_imports/source.py
test/unit3/test_import/data/circular_imports/subpackage.py
test/unit3/test_import/data/circular_imports/subpkg/subpackage2.py
test/unit3/test_import/data/circular_imports/subpkg/util.py
test/unit3/test_import/data/circular_imports/use.py
test/unit3/test_import/data/circular_imports/util.py
test/unit3/test_import/data/package/__init__.py
test/unit3/test_import/data/package2/submodule1.py
test/unit3/test_import/data/unwritable/__init__.py

In cpython import lib checks a module's spec to see if it's initializing
If it's initializing then a `"most likely due to a circular import"` error message is thrown.
We don't have specs in skulpt.
Instead, I add a `.$initializing` attribute to modules before we eval them.
Since a `relativePackage` is responsible for importing its leaf modules, I add the same attribute to the `relativePackage` (if it's not already in the initializing state).
I added the Circular Import tests from Cpython and tweaked them slightly.
Most tests failed because skulpt thought there were circular imports going on that weren't
That seemed to be because the `relativePackage` didn't know anything about the module it was importing early enough.
To fix this I add the module as an attribute to the `relativePackage` …

make circular import errors work with current import implementation

---

src/import.js
test/unit3/test_import/__init__.py

fix regression from #1419 
Javascript scoping rules meant that the formName was not scoped correctly
This Pr fixes that
(prior to #1419 we nested the call at each iteration, which meant we didn't need to worry about scoping in the same way)

Fix nesting import chaining

---

src/builtindict.js
src/import.js
test/unit3/test_builtin.py

tests taken from cpython
I think the the `__import__` implementation is fairly well tested since it's part of our compile code,
so really this pr just supports actually calling `__import__` from python code.
Which currently just breaks because it expects javascript types.
I do some type checking but also do the lazy thing of just remapping the objects to javascript since:
- from list should be a tuple/list of strings, and
- level should be an integer

Implement __import__

---

src/compile.js

Whenever my Python program times out, I get the following error: `ExternalError: TypeError: Sk.builtin.TimeLimitError is not a constructor on line undefined`. This happens because `TimeLimitError` has been changed to `TimeoutError`.
A very small change but this fixes the problem.

Changed TimeLimitError to TimeoutError in compile.js

---

src/constants.js
src/module.js
src/object.js
src/type.js
test/unit/test_deepcopy.py
test/unit3/test_descr.py

This pr implements `__slots__`
it's 1 commit ahead of #1092 
For the diff see the last commit on this pr or you can check it out here: 590d8ac
It includes all the tests from cpython unittests (with a couple of edge cases commented out)
I also needed to implement `isidentifier` for `str`
The copy module does't work for classes that define `__slots__` but since `__slots__` previously wasn't supported, copying them wouldn't really have worked anyway.
(to fix the copy module we can look to define the `__reduce_ex__` descriptor)
closes #1050

Implement __slots__

---

src/property_class_static.js
src/super.js

Not particularly easy to add tests for this since python attribute access, when compiled to javascript, checks for suspensions
But it will be an issue for any internal code that expects `tp$gettattr` or `Sk.abstr.gattr` to not suspend unexpectedly.

fix property and super should be suspension aware

---

src/compile.js
test/unit3/test_decorators.py

This fixes the order in which decorators are applied to classes.
Previously this was fixed for functions in #1149. The same fix is applied in this PR.
I also added a test for this, and extended the existing test for functions.

Fix: multiple class decorators applied in wrong order

---

src/set.js

printing a frozenset causes an error since the `in$repr` property was non writable.
This pr fixes that.

fix frozenset has a non-writable property

---

src/abstract.js

I had some code where a python string leaked into a keyword array when it should have been a javascript string
This tweak accounts for that leak
The leak itself was our own doing, but it's probably best to handle it nicely.

Minor tweak to copyKeywordsToNamedArgs

---

src/slotdefs.js

For internal calls to `tp$descr_get` we should send both the instance and the type argument.
Whilst most builtins that use `__get__` cope without the second argument, it's possible that a custom `__get__` will expect it to be there.
(I found this recently with another library).
Quite a small change, I don't think it really needs any additional tests since the call signature to `__get__` is typically `def __get__(self, __obj: Any, __type: type | None = None) -> Any:`

Always provide the second argument to `tp$descr_get`

---

src/compile.js

Currently the breakpoint in a while loop is set to be after the test.
This means that when implementing a line by line debugger, the final
test that causes the while loop to terminate is not shown. By changing
the position of the debug block, the final test will be shown.

Change breakpoint in while statement for debugging

---

src/compile.js

Fix a bug from recent PRs
In a previous PR we declared a variable for the instance that would be passed to `super()`
(previous to that PR the instance to `super()` was always assumed to be variable named `self` but it could easily be `cls` for a classmethod).
But the compile code ended up with a bug
```js
var $sup = self = args[0], ...;
```
Now fixed to be
```js
var self = args[0], ..., $sup = self;
```
The former overrides the global self - i.e. window.self! 😬
The latter uses the locally scoped self ☑️

fix bad variable declaration in compile code.

---

src/function.js
test/unit3/test_funcattrs.py

I found a use case for being able to override `__defaults__`.
This PR makes `__defaults__` a writable attribute.
I added the tests from the cpython test module `test_funcattrs.py`
Any other tests commented out in that file are beyond the scope of this PR
But should probably be addressed at some point

func.__defaults__ should have a set method

---

src/abstract.js
src/constants.js
src/object.js
src/type.js
test/unit3/test_descr.py

If you like reading c - here are the implementations that I was following
`type__dir__`:
https://github.com/python/cpython/blob/fea7290a0ecee09bbce571d4d10f5881b7ea3485/Objects/typeobject.c#L4280-L4291
`object__dir__`:
https://github.com/python/cpython/blob/fea7290a0ecee09bbce571d4d10f5881b7ea3485/Objects/typeobject.c#L5564-L5609
`merge_class_dict`:
https://github.com/python/cpython/blob/fea7290a0ecee09bbce571d4d10f5881b7ea3485/Objects/typeobject.c#L4215-L4267
It's probably a slower implementation - but looking up the `__dir__` is mostly for introspection.
It's also more correct - I was able to uncomment a test that would have previously failed.
It came up when overriding the `__dict__` property and discovered that cpython uses the return value from `__dict__`, rather than the internal …

dir: make it match cpython

---

src/tuple.js

Hard to test exactly since it will still throw an IndexError, but the message is corrected in this PR
```python
>>> x = (1, 2, 3, 4)
>>> x[2**75]
IndexError: cannot fit 'int' into an index-sized integer
```
This PR brings tuple.js inline with what's already there in list.js
If an error class isn't supplied to `asIndexSized` then then if the index is too large it will be returned as `±Number.MAX_SAFE_INTEGER`.
So this PR doesn't change the ultimately thrown IndexError, but it does fix the error message, since it gets thrown on line 85 rather than a few lines later.

fix: error message with an index that's too large

---

README.md

The [blog post link](http://reputablejournal.com/adding-a-module-to-skulpt.html) seems to be dead. This commit merely removes it from the readme.

Remove dead link from readme

---

src/builtin.js
src/lib/re.js
src/mappingproxy.js
support/polyfills/JSBI.js
support/polyfills/es6.js
test/run/t460.py
test/run/t460.py.real
test/unit3/test_re.py

This is an attempt to enhance the features in skulpt's regex implementation.
- `re.RegexFlag` implemented - with a metatype!
`list(re.RegexFlag) # [re.ASCII, re.UNICODE, ...]`
- `re.RegexFlag` is a subtype of `int`
missing methods implemented - `sub`, `subn`, `escape`, `findall`, `finditer`
fixes `re.split` for capture groups
support for named capture groups
```python
>>> re.compile('(?P<foo>)').groups
1
>>> re.compile('(?P<foo>)').groupindex
{foo: 1}
```
tests taken from cpython and as many tests as possible uncommented.
There are still unsupported features since python and javascript regex is different!
There also may be some edge cases where compilation between python and javascript is different.
If anyone has an extensive regex implementation in their skulpt - it would be great to see …

an update regex module

---

src/lib/json.js
src/lib/json/__init__.py
src/lib/json/tests/__init__.py
test/unit3/test_json.py

1 commit ahead of #1191.
(Only look at the final commit in this pr to see the implementation)
I wanted to use the ffi branch for this because it allows hook functions into `toJs`
The hook functions are used in this implementation of `dumps`.
Based largely on the python json implementation.
This PR implements `dumps`, `loads` and `JSONDecodeError` with tests from CPython.
Some differences to python
`dump`, `load`, `JSONDecoder` and `JSONEncoder` are not implemented.
`strict` is ignored when passed to `loads`.
`ensure_ascii` is ignored when passed to `dumps`.
using `cls` or other keyword arguments throws.

implement json

---

src/ffi.js

We shouldn't reference window directly since it doesn't exist in say a web worker

ffi: remove reference to window

---

src/builtin/sys.js
src/complex.js
src/float.js
src/int.js
src/lib/fractions.js
src/lib/math.js
test/run/t498.py
test/run/t498.py.real
test/unit3/test_builtin.py
test/unit3/test_fractions.py

Implement fractions module in javascript with tests
required changes:
- adjust hashing of ints/floats
- sys.hash_info
- implement -float ** fractional power (comment out python 2 test that says this is not allowed)

fractions module

---

src/property_class_static.js
test/unit3/test_decorators.py

allows property to be subclassed correctly
and fixes doc issues from the test, uncommenting out some tests from the test suite

property fixes

---

src/dict.js
src/generic.js
test/unit3/test_skulpt_bugs.py

`mp$ass_subscript` is overridden by `__setitem__`
And if strangely if you override the `__dict__` of an object with a dict subclass, this method is never called.
Minor change
Just for correctness
I couldn't find any CPython tests for this, so I added a custom test and ran it against Cpython
I changed the name of `set$item` to `dict$setItem` to better match cPython's `_pyObjectDict_SetItem`

dict: fix setattr should not call mp$ass_subscript on the `__dict__`

---

src/ffi.js

At the moment symbols get lost in the ffi toPy/toJs conversion
And if you're doing something crazy like getting a ReactComponent inside Skulpt
then you get:
```python
{'$$typeof': Symbol(react.element), ...}
```
So it helps if you can handle Symbols
(Small change)

ffi: wrap Symbols

---

src/ffi.js
test/unit3/test_skulpt_interop.py

Currently when we interop with javascript objects on window,
if we get an array, we return a python copy of this array
I've found this to be problematic since,
- we lose mutability
- some javascript libraries do crazy things with arrays
(See below)
When returning an Array from a proxied javascript object
This PR instead returns a ProxyList
Which is very similar to a python list (it's even a subclass)
But, the internal Array is a Proxy of the original Javascript Array
Now we essentially have the same reference and mutating the ProxyList mutates the original list
I've added tests to demonstrate this interopability
---
Example in an app we had failing:
```javascript
// initial page script
function(){var analytics=window.analytics=window.analytics||[];//...}
```
The script used an array as a …

ffi: preserve arrays on javascript objects

---

src/dict.js
src/ffi.js
src/set.js
test/unit3/test_skulpt_interop.py

This PR changes how we proxy Maps and Sets from javascript to python
previously if a javascript library returned a Map or a Set we would receive a python dict/set respectively
This is problematic since the objects lose mutability
In this PR we create ProxyMap and ProxySet that are subclasses of dict/set
These proxy versions mean we maintain mutability
And it's also backwards compatible

ffi - map and set behaviour

---

src/ffi.js
test/unit3/test_skulpt_interop.py

fix for reassigning a proxied list back to a javascript api
(small change with a test)

ffi: fix re-assign list to window should be the same object

---

src/ffi.js
test/unit3/test_skulpt_interop.py

The failing test would give you
```
TypeError: 'get' on proxy: property '0' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '1' but got '[object Object]')
```
So if we encounter a frozen list, then don't use a proxylist, just use a standard python list

Fix can't use a proxy list on a frozen array

---

src/ffi.js
src/method.js
test/unit3/test_skulpt_interop.py

Use case
```python
import document
from time import sleep
class Foo:
def on_mount(self):
document.addEventListener("click", self.on_click)
def on_cleanup(self):
document.removeEventListener("click", self.on_click)
def on_click(self, event):
print("document was clicked")
foo = Foo()
foo.on_mount()
sleep(3)
foo.on_cleanup()
```
We would expect that the above code to successfully clean up the click event handler
But currently this doesn't work
the equivalent code would work in javascript because bound methods are identical
whereas in python two methods are not identical
```python
>>> foo.on_click is foo.on_click
False
>>> foo.on_click == foo.on_click
True
```
```javascript
>>> class Foo { bar() {}}
>>> var foo = new Foo()
>>> foo.bar === foo.bar
true
```
This is a big gotcha for event …

ffi: preserve identity of methods into javascript

---

src/ffi.js
test/unit3/test_skulpt_interop.py

Advanced use case of the ffi module is to have an iframe in python and post messages to the iframe's `contentWindow`
When we access the `contentWindow` we try to convert this object to a python object.
But we break the browser's same origin policy when we access properties like `sk$object` or `$isPyWrapped` when determining what type of object we are converting to python.
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#window
This PR adds a check in the Proxy object lookup to determine if the attribute is a cross origin window object
If it is, we shortcut the code and return a Proxy object rather than going through `toPy`.
I added tests that can be run in the browser
But these tests won't run in a node environment

ffi: fix converting cross origin windows to python

---

.github/workflows/test.yml
src/bytes.js
test/unit3/test_bytes.py

while encoding in the browser is only valid for utf8,
the browser's TextDecoder supports various decode encodings
https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API/Encodings
This PR uses the browsers decode implementation if available
adds a couple of tests

bytes: support decode encodings that the browser supports #noa

---

src/constants.js
src/property_class_static.js
test/unit3/test_decorators.py
test/unit3/test_descr.py

in python 310 some enhancements were made to class/staticmethod
> Static methods ([@staticmethod](https://docs.python.org/3.10/library/functions.html#staticmethod)) and class methods ([@classmethod](https://docs.python.org/3.10/library/functions.html#classmethod)) now inherit the method attributes (__module__, __name__, __qualname__, __doc__, __annotations__) and have a new __wrapped__ attribute. Moreover, static methods are now callable as regular functions. (Contributed by Victor Stinner in [bpo-43682](https://bugs.python.org/issue?@action=redirect&bpo=43682).)
This PR adds support for this feature and copies the tests from cpython

decorators: add 3.10 changes to static/class methods

---

gen/astnodes.js
src/ast.js

This was added in python 3.10
I overrode the astnodes.js file manually
I think that's fine for now
Reason for the change, if we know the alias position then it makes a jump to definition implementation easier from the ast.

Feat: add lineno, col_offset support for alias

---

src/ast.js
src/builtindict.js
src/function.js
src/generic_alias.js
src/lib/collections.js
src/lib/datetime.js
src/lib/json.js
src/object.js
src/str.js
src/super.js
src/type.js

Motivation:
str interning for a long running python program could use a lot of memory
our current implementation is also not quite the same as cpython
Our constants are cached during compilation so tests that look for compiled str identity will still work
I actually didn't need to change any tests here.
I adjusted places where we rely on str identity in the code base
This reliance also meant implementing `tp$hash` for `Sk.builtin.str`
(The python 2.7 [implementation](https://github.com/python/cpython/blob/2.7/Objects/unicodeobject.c#L6654) is much easier to follow so I used that)
I adjusted the internals of `$name` for `Sk.builtin.func` to be a python string.
There was a test for this in `test_functools` that expected `__name__` to be identical after wrapping

string interning: don't do it - rely on compiled constants

---

src/compile.js
src/str.js

builds on top of #1571 
(see last commit)
I mistakenly thought that compiled strings were already interned
but actually this happens on a per scope basis
I think it's probably worth including this PR so that something like this works
```python
def check(x):
for x in ("123", "abc"):
print(x is y)
check("123") # True, False
check("abc") # False, True
```
In Skulpt, after #1481  we get False values because constants in different scopes are not identical
But in CPython we get True values for str literals interned at compile time

Intern compiled strings

---

src/env.js
src/ffi.js
src/misceval.js

This PR builds on #1496 and you only need to look at the final commit
This PR changes the semantics of how python Callables sent to javascript work
Example when we would trigger this logic
```python
import document
btn = document.getElementById("my-button")
def button_click(event):
...
btn.addEventListener("click", button_click)
```
The current implementation:
- if a Python function is called from JavaScript (as would happen above when a button is clicked)
- then if the function suspends and the suspension is optional, we skip it
- if the function suspends and is not optional, we return a Promise (e.g. a `sleep(4)`)
The problem:
- If you are using Skulpt's breakpoints
- then you want the python function to suspend
- even when it is used as a callback in javascript
This PR adds some logic …

Add debug suspension logic to ffi python callbacks

---

src/ffi.js

We've had users wrapping javascript libraries built using comlink js objects
and this small change means that these libraries are usable in skulpt
---
**how the current code fails:**
whenever a `comlink` object does attribute look up, it returns a proxy function
so we were asking a `comlink` object for it's `sk$object` attribute, and it was happily providing us with something.
**how this change fixes this edge case**
`comlink` objects are proxies and don't override the `.has` method trap, and so if we ask for `"sk$object" in obj` we get `false`.
And then everything works.
proxies are notoriously difficult to introspect
there will probably be more edge cases in the future
this change helps with an edge case we've seen a couple of times now
and it won't change semantics for existing success …

Fix object type checks in FFI for obscure objects in python

---

src/builtin.js
test/unit/test_StringIO.py

Currently input() is behaving in a non-expected manner in two ways:
- If the `input` function takes a prompt, then `Sk.builtin.file.$readline` is hard-coded to be used, even if `sys.stdin` has been replaced by a `StringIO` object. This function expects the internal structure of a `file` and results in errors if the `sys.stdin` has been redirected to a `StringIO`.
- When `input` uses `readline` to read, it does not remove the possible newline character at the end of the line. This results in somewhat inaccurate behavior in multi-line input cases.
This PR addresses these issues by only using `$readline` in the case where `sys.stdin` has not been replaced, and by trimming the newline character if present on the normal `readline` call.

Improve behavior of input() when using non-default sys.stdin

---

src/compile.js
test/unit3/test_skulpt_bugs.py

added failing test case to highlight the issue
mirrors cpython compile code at the same line
https://github.com/python/cpython/blob/1793b7291f4c360ccbbf13a110abbcdf89c65aec/Python/compile.c#L5933

fix: support tuple unpacking in with statement context manager
